require("dotenv").config();
const mongoose = require("mongoose");
const Link = require("./models/Link");

// Connect to the database
mongoose
  .connect(process.env.MONGO_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => console.log("Database connected"))
  .catch((err) => console.error("Database connection error:", err));

// Example data to seed the `Link` collection
const seedData = [
  { url: "https://www.instagram.com/ritualcuerpoyalma/" },
  { url: "https://www.instagram.com/septemberdaviss/" },
  { url: "https://www.instagram.com/talha.ghazi_3/" },
  { url: "https://www.instagram.com/gcc_exhibition/" },
  { url: "https://www.instagram.com/oceanicmedia_/" },
  { url: "https://www.instagram.com/ohmunch/" },
  { url: "https://www.instagram.com/thetacohouseldn/" },
  { url: "https://www.instagram.com/beverageboutique/" },
  { url: "https://www.instagram.com/creekcarver/" },
  { url: "https://www.instagram.com/santyortizz/" },
  { url: "https://www.instagram.com/foodsnapp__/" },
  { url: "https://www.instagram.com/peachpropertiesuk/" },
  { url: "https://www.instagram.com/visionary.lab/" },
  { url: "https://www.instagram.com/westlondon_businesses/" },
  { url: "https://www.instagram.com/ndobiz/" },
  { url: "https://www.instagram.com/britnedionne/" },
  { url: "https://www.instagram.com/joinbulba/" },
  { url: "https://www.instagram.com/halal_accreditation/" },
  { url: "https://www.instagram.com/life.with.luna.love/" },
  { url: "https://www.instagram.com/eatand_drinkwithalisha/" },
  { url: "https://www.instagram.com/hankiespiccadilly/" },
  { url: "https://www.instagram.com/youmesushi/" },
  { url: "https://www.instagram.com/4youexpress2022/" },
  { url: "https://www.instagram.com/growthwave_consultancy/" },
  { url: "https://www.instagram.com/doubleupsocial/" },
  { url: "https://www.instagram.com/drivingschoolinuk65/" },
  { url: "https://www.instagram.com/currywalamedia/" },
  { url: "https://www.instagram.com/omgitsufi/" },
  { url: "https://www.instagram.com/potandrice/" },
  { url: "https://www.instagram.com/trendy_genius/" },
  { url: "https://www.instagram.com/explodesocialmedia/" },
  { url: "https://www.instagram.com/electricwednesdayband/" },
  { url: "https://www.instagram.com/menaw333/" },
  { url: "x1i10hfl href" },
  { url: "https://www.instagram.com/georgiehphotos/" },
  { url: "https://www.instagram.com/alijmiller30/" },
  { url: "https://www.instagram.com/tlixali/" },
  { url: "https://www.instagram.com/meganmayday/" },
  { url: "https://www.instagram.com/omos_corner/" },
  { url: "https://www.instagram.com/brittanypelka/" },
  { url: "https://www.instagram.com/whiskeywebwhatnot/" },
  { url: "https://www.instagram.com/mstonevallc/" },
  { url: "https://www.instagram.com/postpartumnetwork/" },
  { url: "https://www.instagram.com/aylauarte/" },
  { url: "https://www.instagram.com/jenahowerton/" },
  { url: "https://www.instagram.com/_yourdream_life/" },
  { url: "https://www.instagram.com/sammareats/" },
  { url: "https://www.instagram.com/styled.bystef/" },
  { url: "https://www.instagram.com/fashionistanyc/" },
  { url: "https://www.instagram.com/the.tamar.altschuler/" },
  { url: "https://www.instagram.com/ourlackawannalife/" },
  { url: "https://www.instagram.com/tlixali.b/" },
  { url: "https://www.instagram.com/itsfinajay/" },
  { url: "https://www.instagram.com/skiesbamboo/" },
  { url: "https://www.instagram.com/candylovesbeauty2/" },
  { url: "https://www.instagram.com/unapologeticallyflawed42/" },
  { url: "https://www.instagram.com/jerseyallan/" },
  { url: "https://www.instagram.com/clevelandfashionista/" },
  { url: "https://www.instagram.com/themartinezfamily817/" },
  { url: "https://www.instagram.com/theeolivegirly/" },
  { url: "https://www.instagram.com/thebrown_diary/" },
  { url: "https://www.instagram.com/boookkeepingbydanni/" },
  { url: "https://www.instagram.com/beautytealove_review/" },
  { url: "https://www.instagram.com/chloebarriercreative/" },
  { url: "https://www.instagram.com/adventures.of.a.pa.momma/" },
  { url: "https://www.instagram.com/fitness.with.jolene/" },
  { url: "https://www.instagram.com/midlifelifestyle/" },
  { url: "https://www.instagram.com/esquaredmarketing/" },
 
  { url: "https://www.instagram.com/nacmediagroup/" },
  { url: "https://www.instagram.com/the_conciergeagency/" },
  { url: "https://www.instagram.com/elyseecollective/" },
  { url: "https://www.instagram.com/tmcpr_/" },
  { url: "https://www.instagram.com/starkmatthews/" },
  { url: "https://www.instagram.com/elisegarlandpublicrelations/" },
  { url: "https://www.instagram.com/theaudienceagency/" },
  { url: "https://www.instagram.com/twobirdstalking/" },
  { url: "https://www.instagram.com/countryroadhome/" },
  { url: "https://www.instagram.com/coote.agency/" },
  { url: "https://www.instagram.com/stella_co_/" },
  { url: "https://www.instagram.com/evh.agency/" },
  { url: "https://www.instagram.com/indiannaroehrich/" },
  { url: "https://www.instagram.com/romanobeck/" },
  { url: "https://www.instagram.com/catinella.pr/" },
  { url: "https://www.instagram.com/ggpragency/" },
  { url: "https://www.instagram.com/chic_digital_creative/" },
  { url: "https://www.instagram.com/sophiemcgrathpr/" },
  { url: "https://www.instagram.com/itsallgpr/" },
  { url: "https://www.instagram.com/ampr_group/" },
  { url: "https://www.instagram.com/hushcommunications/" },
  { url: "https://www.instagram.com/morganhillcommunications/" },
  { url: "https://www.instagram.com/echocommunicationpr/" },
  { url: "https://www.instagram.com/mcm_pr/" },
  { url: "https://www.instagram.com/omjewellery.syd/" },
  { url: "https://www.instagram.com/amsupply_menswear/" },
  { url: "https://www.instagram.com/flourish_pr/" },
  { url: "https://www.instagram.com/onetwoagency_/" },
  { url: "https://www.instagram.com/maxmedialab/" },
  { url: "https://www.instagram.com/idcollective/" },
  { url: "https://www.instagram.com/melbournesocialco/" },
 
  { url: "https://www.instagram.com/freecryptosfaucets/" },
  { url: "https://www.instagram.com/lootsource/" },
  { url: "https://www.instagram.com/sweateconomy/" },
  { url: "https://www.instagram.com/jetongame/" },
  { url: "https://www.instagram.com/rewardyapp/" },
  { url: "https://www.instagram.com/orarewards/" },
  { url: "https://www.instagram.com/freecash.com_/" },
  { url: "https://www.instagram.com/linkfly.to/" },
  { url: "https://www.instagram.com/timewallio/" },
  { url: "https://www.instagram.com/adkeeps/" },
  { url: "https://www.instagram.com/exchange_giftcard_store/" },
  { url: "https://www.instagram.com/lootupme/" },
  { url: "https://www.instagram.com/paidcash_co/" },
  { url: "https://www.instagram.com/cryptoidleminer/" },
  { url: "https://www.instagram.com/honeygain_app/" },
  { url: "https://www.instagram.com/satsfaucet/" },
  { url: "https://www.instagram.com/sidehustle.hacks/" },
  { url: "https://www.instagram.com/sweat.influencer/" },
  { url: "https://www.instagram.com/sweat.economy/" },
  { url: "https://www.instagram.com/zapsurveysapp/" },
  { url: "https://www.instagram.com/linkme/" },
  { url: "https://www.instagram.com/coinsbaron_com/" },
  { url: "https://www.instagram.com/vid.earn/" },
  { url: "https://www.instagram.com/hossin01234567/" },
  { url: "https://www.instagram.com/identistry_uz/" },
  { url: "https://www.instagram.com/1wingroup/" },
  { url: "https://www.instagram.com/liolan_tech/" },
  { url: "https://www.instagram.com/poppolivestream/" },
  { url: "https://www.instagram.com/epicstoryofmonsters/" },
  { url: "https://www.instagram.com/jayecane/" },
  { url: "https://www.instagram.com/voice.bb/" },
  { url: "https://www.instagram.com/americaopinaoficial/" },
  { url: "https://www.instagram.com/sweatcoin_design/" },
  { url: "https://www.instagram.com/fruitblitz/" },
  { url: "https://www.instagram.com/_saudita/" },
  { url: "https://www.instagram.com/poppolive_official/" },
  { url: "https://www.instagram.com/dailyraffleapp/" },
  { url: "https://www.instagram.com/mohsen_ahmed10/" },
  { url: "https://www.instagram.com/earnitzreward/" },
  { url: "https://www.instagram.com/no.planches/" },
  { url: "https://www.instagram.com/yoowko/" },
  { url: "https://www.instagram.com/osi_hcm/" },
 
  { url: "https://www.instagram.com/sinnamon_pr/" },
  { url: "https://www.instagram.com/serviceinsider/" },
  { url: "https://www.instagram.com/beauty_bulletin/" },
  { url: "https://www.instagram.com/nfluence_pr/" },
  { url: "https://www.instagram.com/bridge.management/" },
  { url: "https://www.instagram.com/menlynmaineluxuryrentals/" },
  { url: "https://www.instagram.com/collabco.za/" },
  { url: "https://www.instagram.com/capetowntv_/" },
  { url: "https://www.instagram.com/arcstoreofficial/" },
  { url: "https://www.instagram.com/sasa_awards/" },
  { url: "https://www.instagram.com/actorvate/" },
  { url: "https://www.instagram.com/thorntreemedia/" },
  { url: "https://www.instagram.com/kah_tequila_africa/" },
  { url: "https://www.instagram.com/blackoceanevents/" },
  { url: "https://www.instagram.com/bpgattorneys/" },
  { url: "https://www.instagram.com/be_influncd/" },
  { url: "https://www.instagram.com/140mediagroup/" },
  { url: "https://www.instagram.com/eventoptionssa/" },
  { url: "https://www.instagram.com/coralcommunications/" },
  { url: "https://www.instagram.com/thecreactivemagazine/" },
  { url: "https://www.instagram.com/vip_concierge_za/" },
  { url: "https://www.instagram.com/lume.agency/" },
  { url: "https://www.instagram.com/pridewealthsa/" },
  { url: "https://www.instagram.com/mamamexicanajozi/" },
  { url: "https://www.instagram.com/goodvibeslifestyleagency/" },
  { url: "https://www.instagram.com/humanzsouthafrica/" },
  { url: "https://www.instagram.com/eskizzel/" },
  { url: "https://www.instagram.com/mantra_publicity/" },
  { url: "https://www.instagram.com/wow_moms_club/" },
  { url: "https://www.instagram.com/stylesasego.management/" },
  { url: "https://www.instagram.com/capturedby.melu/" },
  { url: "https://www.instagram.com/urithi_marketing/" },
  { url: "https://www.instagram.com/style_id_africa/" },
  { url: "https://www.instagram.com/littlefootprintsza/" },
  { url: "https://www.instagram.com/mfpconnect/" },
  { url: "https://www.instagram.com/vcwe_worldevents/" },
  { url: "https://www.instagram.com/littlegirlarise_sa/" },
  { url: "https://www.instagram.com/thewirelesssa/" },
  { url: "https://www.instagram.com/houseofmariabridalcouture/" },
 
  { url: "https://www.instagram.com/surveypolice/" },
  { url: "https://www.instagram.com/oneplotter/" },
  { url: "https://www.instagram.com/digistore24/" },
  { url: "https://www.instagram.com/bitcoin.com_official/" },
  { url: "https://www.instagram.com/token.course/" },
  { url: "https://www.instagram.com/beermoneyforum/" },
  { url: "https://www.instagram.com/sweat.economy/" },
  { url: "https://www.instagram.com/rollercoin.official/" },
  { url: "https://www.instagram.com/sound.me/" },
  { url: "https://www.instagram.com/limercoin/" },
  { url: "https://www.instagram.com/epiconquest/" },
  { url: "https://www.instagram.com/americaopinaoficial/" },
  { url: "https://www.instagram.com/cryptotabbrowser/" },
  { url: "https://www.instagram.com/databot.app/" },
  { url: "https://www.instagram.com/diycraft04/" },
  { url: "https://www.instagram.com/split.drop/" },
  { url: "https://www.instagram.com/userlyticscorporation/" },
  { url: "https://www.instagram.com/coinsbaron_com/" },
  { url: "https://www.instagram.com/chiefxian03/" },
  { url: "https://www.instagram.com/gooddollarorg/" },
  { url: "https://www.instagram.com/superpayme_official/" },
  { url: "https://www.instagram.com/add_slice/" },
  { url: "https://www.instagram.com/carebuzz_app/" },
  { url: "https://www.instagram.com/promotesweatcoin/" },
  { url: "https://www.instagram.com/pinews2021/" },
  { url: "https://www.instagram.com/tokaizloy/" },
  { url: "https://www.instagram.com/personal_care142/" },
  { url: "https://www.instagram.com/orarewards/" },
  { url: "https://www.instagram.com/dollarsreward/" },
  { url: "https://www.instagram.com/lootsource/" },
  { url: "https://www.instagram.com/microworkerscom/" },
  { url: "https://www.instagram.com/swarupkumardas82/" },
  { url: "https://www.instagram.com/cryptotabme/" },
  { url: "https://www.instagram.com/packellapp/" },
  { url: "https://www.instagram.com/pinetworkcoinbuyerrrr/" },
 
  { url: "https://www.instagram.com/pinetworkteams/" },
  { url: "https://www.instagram.com/arivawonderland/" },
  { url: "https://www.instagram.com/exolo.official/" },
  { url: "https://www.instagram.com/shiba_army_63/" },
  { url: "https://www.instagram.com/klever.io/" },
  { url: "https://www.instagram.com/eaglenetworkapp/" },
  { url: "https://www.instagram.com/wallacecryptowallet/" },
  { url: "https://www.instagram.com/kryptomonteam/" },
  { url: "https://www.instagram.com/hunnyplay_/" },
  { url: "https://www.instagram.com/airdroptoken_official/" },
  { url: "https://www.instagram.com/earndogecoin.app/" },
  { url: "https://www.instagram.com/cropbytesofficial/" },
  { url: "https://www.instagram.com/bluemoon.io_/" },
  { url: "https://www.instagram.com/mojaik_official/" },
  { url: "https://www.instagram.com/rollercoin.official/" },
  { url: "https://www.instagram.com/coinsbit.io/" },
  { url: "https://www.instagram.com/azbit.news/" },
  { url: "https://www.instagram.com/pinews2021/" },
  { url: "https://www.instagram.com/foneblockchain/" },
  { url: "https://www.instagram.com/bitslersport/" },
  { url: "https://www.instagram.com/cryptotabme/" },
  { url: "https://www.instagram.com/limercoin/" },
  { url: "https://www.instagram.com/liquidus_finance/" },
  { url: "https://www.instagram.com/official_pixelmon/" },
  { url: "https://www.instagram.com/chainersnft/" },
  { url: "https://www.instagram.com/illuviumio/" },
  { url: "https://www.instagram.com/thousandtoken/" },
  { url: "https://www.instagram.com/starnetwork.io/" },
  { url: "https://www.instagram.com/_eternalleague_/" },
  { url: "https://www.instagram.com/beatbindgram/" },
  { url: "https://www.instagram.com/trustdice.win/" },
  { url: "https://www.instagram.com/mechcraft.world/" },
  { url: "https://www.instagram.com/coinsbaron_com/" },
  { url: "https://www.instagram.com/cryptotabbrowser/" },
  { url: "https://www.instagram.com/bydfi_official/" },
  { url: "https://www.instagram.com/coinomiofficial/" },
  { url: "https://www.instagram.com/natixnetwork/" },
 
  { url: "https://www.instagram.com/1wingroup/" },
  { url: "https://www.instagram.com/sound.me/" },
  { url: "https://www.instagram.com/limercoin/" },
  { url: "https://www.instagram.com/carebuzz_app/" },
  { url: "https://www.instagram.com/attapollteam/" },
  { url: "https://www.instagram.com/cheelee.cis/" },
  { url: "https://www.instagram.com/foneblockchain/" },
  { url: "https://www.instagram.com/beermoneyforum/" },
  { url: "https://www.instagram.com/rollercoin.official/" },
  { url: "https://www.instagram.com/risefortheworld/" },
  { url: "https://www.instagram.com/tapnation.io/" },
  { url: "https://www.instagram.com/sweateconomy/" },
  { url: "https://www.instagram.com/cryptotabme/" },
  { url: "https://www.instagram.com/sweat.economy/" },
  { url: "https://www.instagram.com/microworkerscom/" },
  { url: "https://www.instagram.com/pinews2021/" },
  { url: "https://www.instagram.com/lootupme/" },
  { url: "https://www.instagram.com/add_slice/" },
  { url: "https://www.instagram.com/orarewards/" },
  { url: "https://www.instagram.com/sidehustle.hacks/" },
  { url: "https://www.instagram.com/claimcoin.in/" },
  { url: "https://www.instagram.com/gooddollarorg/" },
  { url: "https://www.instagram.com/coinsbaron_com/" },
  { url: "https://www.instagram.com/diycraft04/" },
  { url: "https://www.instagram.com/userlyticscorporation/" },
  { url: "https://www.instagram.com/cryptotabbrowser/" },
  { url: "https://www.instagram.com/sharov_ruslan_/" },
  { url: "https://www.instagram.com/mobrog_surveys/" },
  { url: "https://www.instagram.com/cropbytesofficial/" },
  { url: "https://www.instagram.com/packetshare/" },
  { url: "https://www.instagram.com/bitslersport/" },
  { url: "https://www.instagram.com/bake.io/" },
  { url: "https://www.instagram.com/tokaizloy/" },
  { url: "https://www.instagram.com/fideonlinearena/" },
  { url: "https://www.instagram.com/pinetworkcoinbuyerrrr/" },
  { url: "https://www.instagram.com/taskverseglobal/" },
  { url: "https://www.instagram.com/swarupkumardas82/" },
  { url: "https://www.instagram.com/amfhairs/" },
 
  { url: "https://www.instagram.com/ashleekeating/" },
  { url: "https://www.instagram.com/richard_mugica/" },
  { url: "https://www.instagram.com/la__banya/" },
  { url: "https://www.instagram.com/nailsandcospa/" },
  { url: "https://www.instagram.com/liquorsplit_delivery/" },
  { url: "https://www.instagram.com/esmae_music_official/" },
  { url: "https://www.instagram.com/allybritopr/" },
  { url: "https://www.instagram.com/randishinder/" },
  { url: "https://www.instagram.com/doctor_v_/" },
  { url: "https://www.instagram.com/zperf/" },
  { url: "https://www.instagram.com/getonvolume/" },
  { url: "https://www.instagram.com/chainsaw/" },
  { url: "https://www.instagram.com/nuorganic/" },
  { url: "https://www.instagram.com/beinspired.global/" },
  { url: "https://www.instagram.com/groundzero_with_rafael/" },
  { url: "https://www.instagram.com/fanbasis/" },
  { url: "https://www.instagram.com/growwithusagency/" },
  { url: "https://www.instagram.com/karrots_tm/" },
  { url: "https://www.instagram.com/reeraa.boutique/" },
  { url: "https://www.instagram.com/_bitbusiness/" },
  { url: "https://www.instagram.com/iert.bcs/" },
  { url: "https://www.instagram.com/lariall.beauty/" },
  { url: "https://www.instagram.com/thealonsoreyna/" },
  { url: "https://www.instagram.com/mylatkachenko/" },
  { url: "https://www.instagram.com/nft.newsglobal/" },
  { url: "https://www.instagram.com/badasseryfactory/" },
  { url: "https://www.instagram.com/societyoflifecoaches/" },
  { url: "https://www.instagram.com/lariall.official/" },
  { url: "https://www.instagram.com/stephen/" },
  { url: "https://www.instagram.com/chauncysmartt/" },
  { url: "https://www.instagram.com/dillonkivo/" },
  { url: "https://www.instagram.com/flxnsocial/" },
  { url: "https://www.instagram.com/iamdanielpeter/" },
  { url: "https://www.instagram.com/flxn/" },
  { url: "https://www.instagram.com/reeraa_glasses/" },
  { url: "https://www.instagram.com/darbalthazarmua/" },
  { url: "https://www.instagram.com/youtaas.opal/" },
  { url: "https://www.instagram.com/dankandcybin/" },
  { url: "https://www.instagram.com/reeraa_influencer/" },
  { url: "https://www.instagram.com/naturcelsport/" },
  { url: "https://www.instagram.com/joonweest/" },
  { url: "https://www.instagram.com/trustn/" },
  { url: "https://www.instagram.com/edgeenergyusa/" },
  { url: "https://www.instagram.com/antoinesallis/" },
  { url: "https://www.instagram.com/barbarasanchezpr/" },
  { url: "https://www.instagram.com/thebullevans/" },
  { url: "https://www.instagram.com/jayecane/" },
  { url: "https://www.instagram.com/katie.melissa/" },
  { url: "https://www.instagram.com/nxtfriday/" },
  { url: "https://www.instagram.com/ericdalius/" },
  { url: "https://www.instagram.com/wilsonstillrunning/" },
  { url: "https://www.instagram.com/rdpremiumdrinks/" },
  { url: "https://www.instagram.com/dylanvanas/" },
  { url: "https://www.instagram.com/sanjevofficial/" },
  { url: "https://www.instagram.com/ethanfilmz/" },
  { url: "https://www.instagram.com/cams/" },
  { url: "https://www.instagram.com/gaige/" },
  { url: "https://www.instagram.com/elite_fitness.ig/" },
  { url: "https://www.instagram.com/the_social._.hub/" },
  { url: "https://www.instagram.com/seandelaneyofficial/" },
  { url: "https://www.instagram.com/ceoapexmarketing/" },
  { url: "https://www.instagram.com/thevictoriakennedy/" },
  { url: "https://www.instagram.com/dladdfit/" },
  { url: "https://www.instagram.com/_iitsnicofficial_/" },
  { url: "https://www.instagram.com/pearpop/" },
  { url: "https://www.instagram.com/hoo.be/" },
  { url: "https://www.instagram.com/glitznglam.glampress/" },
  { url: "https://www.instagram.com/viralxagency/" },
 
  { url: "https://www.instagram.com/elyseecollective/" },
  { url: "https://www.instagram.com/jag_aus/" },
  { url: "https://www.instagram.com/dec_pr/" },
  { url: "https://www.instagram.com/nationalfashioncollege/" },
  { url: "https://www.instagram.com/nacmediagroup/" },
  { url: "https://www.instagram.com/ggpragency/" },
  { url: "https://www.instagram.com/kearnspr/" },
  { url: "https://www.instagram.com/adhesive.agency/" },
  { url: "https://www.instagram.com/neonblackcomms/" },
  { url: "https://www.instagram.com/tmcpr_/" },
  { url: "https://www.instagram.com/papaya_agency_/" },
  { url: "https://www.instagram.com/inpresspr/" },
  { url: "https://www.instagram.com/__mhpr__/" },
  { url: "https://www.instagram.com/elisegarlandpublicrelations/" },
  { url: "https://www.instagram.com/janedoecreation/" },
  { url: "https://www.instagram.com/evh.agency/" },
  { url: "https://www.instagram.com/starkmatthews/" },
  { url: "https://www.instagram.com/hatrikhouse/" },
  { url: "https://www.instagram.com/freefolkagency/" },
  { url: "https://www.instagram.com/thearcfactory/" },
  { url: "https://www.instagram.com/thrivepr/" },
  { url: "https://www.instagram.com/humanncomms/" },
  { url: "https://www.instagram.com/ashleighlarden/" },
  { url: "https://www.instagram.com/thegreyconsulting/" },
  { url: "https://www.instagram.com/aremediaaus/" },
  { url: "https://www.instagram.com/theorycrewagency/" },
  { url: "https://www.instagram.com/maxmedialab/" },
  { url: "https://www.instagram.com/theaudienceagency/" },
  { url: "https://www.instagram.com/thegardendistillerygin/" },
  { url: "https://www.instagram.com/img_engage/" },
  { url: "https://www.instagram.com/saundersandcoagency/" },
  { url: "https://www.instagram.com/one_and_one.studio/" },
  { url: "https://www.instagram.com/catinella.pr/" },
  { url: "https://www.instagram.com/wearebuttr/" },
  { url: "https://www.instagram.com/mgmt__/" },
  { url: "https://www.instagram.com/missbrooklynsmith/" },
  { url: "https://www.instagram.com/mcm_pr/" },
 
  { url: "https://www.instagram.com/prettylittlemarketer/" },
  { url: "https://www.instagram.com/girlsinmarketing/" },
  { url: "https://www.instagram.com/socialmediajalyn/" },
  { url: "https://www.instagram.com/thekingmichelle/" },
  { url: "https://www.instagram.com/latermedia/" },
  { url: "https://www.instagram.com/hannahwalkersocial/" },
  { url: "https://www.instagram.com/girlboss/" },
  { url: "https://www.instagram.com/creators/" },
  { url: "https://www.instagram.com/hubspot/" },
  { url: "https://www.instagram.com/artofinfluenceco/" },
  { url: "https://www.instagram.com/socialstocks.co/" },
  { url: "https://www.instagram.com/mosseri/" },
  { url: "https://www.instagram.com/hellostorytale/" },
  { url: "https://www.instagram.com/soaringbirdsocial/" },
  { url: "https://www.instagram.com/sharongillmedia/" },
  { url: "https://www.instagram.com/rootsmarketingagency/" },
  { url: "https://www.instagram.com/socialmoody/" },
  { url: "https://www.instagram.com/_hellomedia/" },
  { url: "https://www.instagram.com/sugarpunchmarketing/" },
  { url: "https://www.instagram.com/semrush/" },
  { url: "https://www.instagram.com/lift.stories/" },
  { url: "https://www.instagram.com/thecreative.social/" },
  { url: "https://www.instagram.com/itsabiconnick/" },
  { url: "https://www.instagram.com/miloupietersz/" },
  { url: "https://www.instagram.com/coastalcollectivemarketing/" },
  { url: "https://www.instagram.com/thelucasokeefe/" },
  { url: "https://www.instagram.com/imdanielaqueiroz/" },
  { url: "https://www.instagram.com/femaleentrepreneurassociation/" },
  { url: "https://www.instagram.com/freelancingfemales/" },
  { url: "https://www.instagram.com/thesocialagency/" },
  { url: "https://www.instagram.com/marketingclairetaylor/" },
  { url: "https://www.instagram.com/the_marketing_millennials/" },
  { url: "https://www.instagram.com/dinahsocials/" },
  { url: "https://www.instagram.com/juliabroome/" },
  { url: "https://www.instagram.com/_socialsam_/" },
  { url: "https://www.instagram.com/briefclub/" },
  { url: "https://www.instagram.com/mailchimp/" },
  { url: "https://www.instagram.com/sociallyybri/" },
  { url: "https://www.instagram.com/iamnatalie/" },
  { url: "https://www.instagram.com/thetomisinsmith/" },
  { url: "https://www.instagram.com/marketingclubmiami/" },
  { url: "https://www.instagram.com/thesocialshells/" },
  { url: "https://www.instagram.com/hootsuite/" },
  { url: "https://www.instagram.com/bound.social/" },
  { url: "https://www.instagram.com/foundr/" },
  { url: "https://www.instagram.com/reelstips/" },
  { url: "https://www.instagram.com/mycontentcollective.co/" },
  { url: "https://www.instagram.com/bm_social_/" },
  { url: "https://www.instagram.com/hashtagmanagedcollective/" },
  { url: "https://www.instagram.com/dearfuturemarketer/" },
  { url: "https://www.instagram.com/sandracreatess/" },
  { url: "https://www.instagram.com/florencejamescollective/" },
  { url: "https://www.instagram.com/samschmidtsocial/" },
  { url: "https://www.instagram.com/elle.social/" },
  { url: "https://www.instagram.com/digitalglowsolutions/" },
  { url: "https://www.instagram.com/julydigitalstudio/" },
  { url: "https://www.instagram.com/laurahaleydt/" },
  { url: "https://www.instagram.com/impactmediahouse/" },
  { url: "https://www.instagram.com/mckennamarketingsolution/" },
  { url: "https://www.instagram.com/millennialsmmarketing/" },
  { url: "https://www.instagram.com/smexaminer/" },
  { url: "https://www.instagram.com/thesocialcreativesclub/" },
  { url: "https://www.instagram.com/the.contentcove/" },
  { url: "https://www.instagram.com/nofiltrsocial/" },
  { url: "https://www.instagram.com/kohi.design/" },
  { url: "https://www.instagram.com/imanimarketingagency/" },
  { url: "https://www.instagram.com/marketingharry/" },
  { url: "https://www.instagram.com/katiesteckly/" },
  { url: "https://www.instagram.com/laurendoesmktg/" },
  { url: "https://www.instagram.com/vicky.owens/" },
  { url: "https://www.instagram.com/the.canov/" },
  { url: "https://www.instagram.com/socialista_media_/" },
  { url: "https://www.instagram.com/iammichellegifford/" },
  { url: "https://www.instagram.com/prgirlmanifesto/" },
  { url: "https://www.instagram.com/alisa.dizzy/" },
  { url: "https://www.instagram.com/mahacopyco/" },
  { url: "https://www.instagram.com/growwithalan/" },
  { url: "https://www.instagram.com/thesocialbungalow/" },
  { url: "https://www.instagram.com/hackinghr/" },
  { url: "https://www.instagram.com/yourtemplateclub/" },
 
  { url: "https://www.instagram.com/inspiredmediaco/" },
  { url: "https://www.instagram.com/sociallyspeakingmedia/" },
  { url: "https://www.instagram.com/coastalcollectivemarketing/" },
  { url: "https://www.instagram.com/revealstudio.co/" },
  { url: "https://www.instagram.com/gg_communications/" },
  { url: "https://www.instagram.com/homemadesocial_/" },
  { url: "https://www.instagram.com/cassklass_/" },
  { url: "https://www.instagram.com/aesthetagroup/" },
  { url: "https://www.instagram.com/girlpowermarketing/" },
  { url: "https://www.instagram.com/bound.social/" },
  { url: "https://www.instagram.com/socialmediajalyn/" },
  { url: "https://www.instagram.com/itssavannahjordan/" },
  { url: "https://www.instagram.com/joinpacksia/" },
  { url: "https://www.instagram.com/i.copywrite_/" },
  { url: "https://www.instagram.com/social.shirley/" },
  { url: "https://www.instagram.com/millennialsmmarketing/" },
  { url: "https://www.instagram.com/thesocialshells/" },
  { url: "https://www.instagram.com/rootsmarketingagency/" },
  { url: "https://www.instagram.com/sociallyybri/" },
  { url: "https://www.instagram.com/thesocialbritify/" },
  { url: "https://www.instagram.com/yourtemplateclub/" },
  { url: "https://www.instagram.com/thepinbar_/" },
  { url: "https://www.instagram.com/mysocialboutique.co/" },
  { url: "https://www.instagram.com/this_is_co._/" },
  { url: "https://www.instagram.com/laurendoesmktg/" },
  { url: "https://www.instagram.com/crushyoursocial/" },
  { url: "https://www.instagram.com/thekingmichelle/" },
  { url: "https://www.instagram.com/ladystrategist/" },
  { url: "https://www.instagram.com/coachfaizus.co/" },
  { url: "https://www.instagram.com/sunnysocialcollective/" },
  { url: "https://www.instagram.com/hashtagmanagedcollective/" },
  { url: "https://www.instagram.com/impactmediahouse/" },
  { url: "https://www.instagram.com/gingerstarrborden/" },
  { url: "https://www.instagram.com/amberfiglow/" },
  { url: "https://www.instagram.com/loudbirdmarketing/" },
  { url: "https://www.instagram.com/shinewithnatasha/" },
  { url: "https://www.instagram.com/mckennamarketingsolution/" },
  { url: "https://www.instagram.com/sisterbrandltd/" },
  

  //--------------------------------------------------------

  
// { url: "https://www.instagram.com/itjausit/" },
// { url: "https://www.instagram.com/swilerpsoftware/" },
// { url: "https://www.instagram.com/syntorix_consulting/" },
// { url: "https://www.instagram.com/maticztechnologies/" },
// { url: "https://www.instagram.com/powermaq_callcenter/" },
// { url: "https://www.instagram.com/cloudmetricsmedia/" },
// { url: "https://www.instagram.com/esoftresponse/" },
// { url: "https://www.instagram.com/softreviewed/" },
// { url: "https://www.instagram.com/twibi_marketing/" },
// { url: "https://www.instagram.com/602_marketing/" },
// { url: "https://www.instagram.com/greatbot.io/" },
// { url: "https://www.instagram.com/all_4_kids_online/" },
// { url: "https://www.instagram.com/bleedingedgetv/" },
// { url: "https://www.instagram.com/s20training/" },
// { url: "https://www.instagram.com/macromindsllc/" },
// { url: "https://www.instagram.com/erfan_kras/" },
// { url: "https://www.instagram.com/diveblastok/" },
// { url: "https://www.instagram.com/hikey_digitalz/" },
// { url: "https://www.instagram.com/it_magician/" },
// { url: "https://www.instagram.com/davetechguy2000/" },
// { url: "https://www.instagram.com/websensei11/" },
// { url: "https://www.instagram.com/macam_services/" },
// { url: "https://www.instagram.com/mali_kdesigns/" },
// { url: "https://www.instagram.com/ajulo_pelumi_felix/" },
// { url: "https://www.instagram.com/paidyet/" },
// { url: "https://www.instagram.com/vseodigital/" },
// { url: "https://www.instagram.com/mift_concepts/" },
// { url: "https://www.instagram.com/eprofessionals2/" },
// { url: "https://www.instagram.com/joesdigitalservices/" },
// { url: "https://www.instagram.com/md.shojibulhasan/" },
// { url: "https://www.instagram.com/taskasaservice_/" },
// { url: "https://www.instagram.com/travel.taralets/" },
// { url: "https://www.instagram.com/centaurdigitalcorp/" },
// { url: "https://www.instagram.com/traffic.fans/" },
// { url: "https://www.instagram.com/socialmedia_umpire/" },

// { url: "https://www.instagram.com/firstclass_globaleducation/" },
// { url: "https://www.instagram.com/aavatechnology/" },
// { url: "https://www.instagram.com/grace.intl/" },
// { url: "https://www.instagram.com/netsmartz_llc/" },
// { url: "https://www.instagram.com/inheritxsolutions/" },
// { url: "https://www.instagram.com/eduskyglobal/" },
// { url: "https://www.instagram.com/idpnepal/" },
// { url: "https://www.instagram.com/studysquarenepal/" },
// { url: "https://www.instagram.com/dot_education/" },
// { url: "https://www.instagram.com/vrittech/" },
// { url: "https://www.instagram.com/eplanetktm/" },
// { url: "https://www.instagram.com/rigorousweb/" },
// { url: "https://www.instagram.com/globaleducc/" },
// { url: "https://www.instagram.com/softnep/" },
// { url: "https://www.instagram.com/blueastral/" },
// { url: "https://www.instagram.com/spintadigital/" },
// { url: "https://www.instagram.com/nzesmumbai/" },
// { url: "https://www.instagram.com/applynec/" },
// { url: "https://www.instagram.com/mararmedia/" },
// { url: "https://www.instagram.com/channelproindia/" },
// { url: "https://www.instagram.com/globalreachsiliguri/" },
// { url: "https://www.instagram.com/spellhosting/" },
// { url: "https://www.instagram.com/aecc.nepal/" },
// { url: "https://www.instagram.com/ioverseaseducation/" },
// { url: "https://www.instagram.com/canamvirtual/" },
// { url: "https://www.instagram.com/analytics_kudil/" },
// { url: "https://www.instagram.com/vidya_vista/" },
// { url: "https://www.instagram.com/brandprovoke/" },
// { url: "https://www.instagram.com/saseducationconsultancy/" },
// { url: "https://www.instagram.com/desireedunepal/" },
// { url: "https://www.instagram.com/espotinternational/" },
// { url: "https://www.instagram.com/eminent_overseas/" },
// { url: "https://www.instagram.com/tatleraddressbook/" },

// { url: "https://www.instagram.com/onlinesalesconsultancy/" },
// { url: "https://www.instagram.com/handscroc/" },
// { url: "https://www.instagram.com/thehiveagencyinsta/" },
// { url: "https://www.instagram.com/newgendepot/" },
// { url: "https://www.instagram.com/zaradigitalau/" },
// { url: "https://www.instagram.com/smartoctopusagency/" },
// { url: "https://www.instagram.com/businesskara/" },
// { url: "https://www.instagram.com/simplybusinessaccounting/" },
// { url: "https://www.instagram.com/makelocalforglobal/" },
// { url: "https://www.instagram.com/ksvfinance/" },
// { url: "https://www.instagram.com/getgrowthexpertz/" },
// { url: "https://www.instagram.com/mrgreatltd/" },
// { url: "https://www.instagram.com/botgotechnologies/" },
// { url: "https://www.instagram.com/spaceddigital/" },
// { url: "https://www.instagram.com/scotworknorthamerica/" },
// { url: "https://www.instagram.com/startbuildlaunch/" },
// { url: "https://www.instagram.com/brand_importance/" },
// { url: "https://www.instagram.com/getbravo.io/" },
// { url: "https://www.instagram.com/content_flip/" },
// { url: "https://www.instagram.com/md.shojibulhasan/" },
// { url: "https://www.instagram.com/orbisterramedia/" },
// { url: "https://www.instagram.com/kardomevoice/" },
// { url: "https://www.instagram.com/lifewithmadsxo/" },
// { url: "https://www.instagram.com/crm_runner/" },
// { url: "https://www.instagram.com/konversable/" },
// { url: "https://www.instagram.com/adzombies/" },
// { url: "https://www.instagram.com/hemel_morrison/" },
// { url: "https://www.instagram.com/die_lautmaler/" },
// { url: "https://www.instagram.com/deliverycloud/" },
// { url: "https://www.instagram.com/wehirepeople1984/" },
// { url: "https://www.instagram.com/akarigouk/" },
// { url: "https://www.instagram.com/cinamonmediahub/" },
// { url: "https://www.instagram.com/bluefinnmedia/" },
// { url: "https://www.instagram.com/myofficesupport/" },
// { url: "https://www.instagram.com/kauz.ai/" },
// { url: "https://www.instagram.com/growwithraydius/" },
// { url: "https://www.instagram.com/gptguides/" },
// { url: "https://www.instagram.com/everything.writing/" },
// { url: "https://www.instagram.com/app_source_hub/" },
// { url: "https://www.instagram.com/ai_prompt_/" },
// { url: "https://www.instagram.com/aust1nmarketing/" },
// { url: "https://www.instagram.com/thesocialalpha_/" },
// { url: "https://www.instagram.com/writewithsneha/" },
// { url: "https://www.instagram.com/adamstewartmarketing/" },
// { url: "https://www.instagram.com/ai.castle/" },
// { url: "https://www.instagram.com/brand.nat/" },
// { url: "https://www.instagram.com/aiforstartups/" },
// { url: "https://www.instagram.com/albicodes/" },
// { url: "https://www.instagram.com/globalglas/" },
// { url: "https://www.instagram.com/tententch/" },
// { url: "https://www.instagram.com/ai.bot._/" },
// { url: "https://www.instagram.com/repentingsoul_13/" },
// { url: "https://www.instagram.com/designerasset/" },
// { url: "https://www.instagram.com/socxplosion/" },

// { url: "https://www.instagram.com/thesocialshells/" },
// { url: "https://www.instagram.com/wordfetti/" },
// { url: "https://www.instagram.com/shecom.co/" },
// { url: "https://www.instagram.com/theconsultingceo/" },
// { url: "https://www.instagram.com/thehouseof.social/" },
// { url: "https://www.instagram.com/_socialsam_/" },
// { url: "https://www.instagram.com/this_is_co._/" },
// { url: "https://www.instagram.com/thedigitalpicnic/" },
// { url: "https://www.instagram.com/coachfaizus.co/" },
// { url: "https://www.instagram.com/smallbusinessgrowthclub/" },
// { url: "https://www.instagram.com/founddlegal/" },
// { url: "https://www.instagram.com/anitasiek/" },
// { url: "https://www.instagram.com/digitalresellvault.official/" },
// { url: "https://www.instagram.com/hero.packaging/" },
// { url: "https://www.instagram.com/aussiebizchic/" },
// { url: "https://www.instagram.com/laurendoesmktg/" },
// { url: "https://www.instagram.com/steviedillon_/" },
// { url: "https://www.instagram.com/freelancinggems/" },
// { url: "https://www.instagram.com/mumswithhustle/" },
// { url: "https://www.instagram.com/tori.packer/" },
// { url: "https://www.instagram.com/minding_her_business/" },
// { url: "https://www.instagram.com/her.social/" },
// { url: "https://www.instagram.com/thatjessab/" },
// { url: "https://www.instagram.com/bishcontentstudio/" },
// { url: "https://www.instagram.com/weareinskinco/" },
// { url: "https://www.instagram.com/shannons.socialmedia/" },
// { url: "https://www.instagram.com/bysamaracribb/" },
// { url: "https://www.instagram.com/theelevatory/" },
// { url: "https://www.instagram.com/theecommercedropout/" },
// { url: "https://www.instagram.com/studio.mayde/" },
// { url: "https://www.instagram.com/ausmumpreneur/" },
// { url: "https://www.instagram.com/thisismiraclaudia/" },
// { url: "https://www.instagram.com/socialmediacal/" },
// { url: "https://www.instagram.com/beboldsocials/" },
// { url: "https://www.instagram.com/mysocialboutique.co/" },
// { url: "https://www.instagram.com/thetshirtco/" },
// { url: "https://www.instagram.com/dashacademy__/" },
// { url: "https://www.instagram.com/heyinfluencers/" },
// { url: "https://www.instagram.com/virtualcassie/" },
// { url: "https://www.instagram.com/bossymummy/" },
// { url: "https://www.instagram.com/liptember/" },
// { url: "https://www.instagram.com/heysocialblonde/" },
// { url: "https://www.instagram.com/bmightie/" },
// { url: "https://www.instagram.com/wilakmedia/" },
// { url: "https://www.instagram.com/ads_haus/" },
// { url: "https://www.instagram.com/ripplevas_official/" },
// { url: "https://www.instagram.com/_work180/" },
// { url: "https://www.instagram.com/socialcrissy/" },
// { url: "https://www.instagram.com/selfamour.au/" },

// { url: "https://www.instagram.com/mindigital.mkt/" },
// { url: "https://www.instagram.com/vidacomvendas/" },
// { url: "https://www.instagram.com/ads2clinic/" },
// { url: "https://www.instagram.com/expertintegrado/" },
// { url: "https://www.instagram.com/gsparanhos/" },
// { url: "https://www.instagram.com/believermktltda/" },
// { url: "https://www.instagram.com/segmenter_/" },
// { url: "https://www.instagram.com/mgmgrowth/" },
// { url: "https://www.instagram.com/amaraldasautomacoes/" },
// { url: "https://www.instagram.com/scaleads_oficial/" },
// { url: "https://www.instagram.com/construsitebrasil/" },
// { url: "https://www.instagram.com/giga.zap/" },
// { url: "https://www.instagram.com/mastertrafegopago/" },
// { url: "https://www.instagram.com/intexfy/" },
// { url: "https://www.instagram.com/agenciamdr/" },
// { url: "https://www.instagram.com/henriquebaptista.ads/" },
// { url: "https://www.instagram.com/mdz.dsgn/" },
// { url: "https://www.instagram.com/holisticmidia/" },
// { url: "https://www.instagram.com/eumauriciotda/" },
// { url: "https://www.instagram.com/salesforyou.com.br/" },
// { url: "https://www.instagram.com/growdocbr/" },
// { url: "https://www.instagram.com/tamojuntoapp.br/" },
// { url: "https://www.instagram.com/papo_ai/" },
// { url: "https://www.instagram.com/waleadsapp/" },
// { url: "https://www.instagram.com/grupo_auge_br/" },
// { url: "https://www.instagram.com/beeviraloficial/" },
// { url: "https://www.instagram.com/dradotrafego/" },
// { url: "https://www.instagram.com/inteligencia.bot/" },
// { url: "https://www.instagram.com/jaqueline.mkt57/" },
// { url: "https://www.instagram.com/omateusandradee/" },
// { url: "https://www.instagram.com/lucafreitas.oficial/" },
// { url: "https://www.instagram.com/bestcontentbrasil/" },
// { url: "https://www.instagram.com/1clickpublicidade/" },
// { url: "https://www.instagram.com/vishanjaliinfo/" },
// { url: "https://www.instagram.com/teckinfosolutions/" },
// { url: "https://www.instagram.com/makewebbetter/" },
// { url: "https://www.instagram.com/brandclever.in/" },
// { url: "https://www.instagram.com/xovient/" },
// { url: "https://www.instagram.com/appsrhino/" },
// { url: "https://www.instagram.com/itinfonity/" },
// { url: "https://www.instagram.com/prologictechnologies/" },
// { url: "https://www.instagram.com/netsmartz_llc/" },
// { url: "https://www.instagram.com/superiormarketingwebsitedesign/" },
// { url: "https://www.instagram.com/kolt_digital/" },
// { url: "https://www.instagram.com/ampdigital.co/" },
// { url: "https://www.instagram.com/univisionz/" },
// { url: "https://www.instagram.com/blueastral/" },
// { url: "https://www.instagram.com/cs_websolutions/" },
// { url: "https://www.instagram.com/pickbettermarketing/" },
// { url: "https://www.instagram.com/zerozillaofficial/" },
// { url: "https://www.instagram.com/hqlsolutions/" },
// { url: "https://www.instagram.com/aarvy_technologies/" },
// { url: "https://www.instagram.com/yugasabot/" },
// { url: "https://www.instagram.com/traitsoft/" },
// { url: "https://www.instagram.com/officialchatbotbuilder/" },
// { url: "https://www.instagram.com/seotowebdesign/" },
// { url: "https://www.instagram.com/invincibledigital/" },
// { url: "https://www.instagram.com/thehrishik/" },
// { url: "https://www.instagram.com/pipaani.marketing/" },
// { url: "https://www.instagram.com/admin.echoinnovateit/" },
// { url: "https://www.instagram.com/growthhackersdigital/" },
// { url: "https://www.instagram.com/neilpateldigitalindia/" },
// { url: "https://www.instagram.com/iksagency/" },
// { url: "https://www.instagram.com/aviox_technologies_/" },
// { url: "https://www.instagram.com/thewavco/" },
// { url: "https://www.instagram.com/lights.camera.social/" },
// { url: "https://www.instagram.com/dizedigital/" },
// { url: "https://www.instagram.com/seositecheckup/" },
// { url: "https://www.instagram.com/mainvps_provider/" },

// { url: "https://www.instagram.com/malewiczhype/" },
// { url: "https://www.instagram.com/toools.design/" },
// { url: "https://www.instagram.com/uxkits/" },
// { url: "https://www.instagram.com/marina_uiux/" },
// { url: "https://www.instagram.com/uix.nerd/" },
// { url: "https://www.instagram.com/humbleteam.agency/" },
// { url: "https://www.instagram.com/figmavibes/" },
// { url: "https://www.instagram.com/rahuldesign.co/" },
// { url: "https://www.instagram.com/uxdesigncollective/" },
// { url: "https://www.instagram.com/anchordesiqn/" },
// { url: "https://www.instagram.com/asanadesignteam/" },
// { url: "https://www.instagram.com/uivirals/" },
// { url: "https://www.instagram.com/ux.fionalim/" },
// { url: "https://www.instagram.com/uxui.heroes/" },
// { url: "https://www.instagram.com/designwithmikey/" },
// { url: "https://www.instagram.com/kris_anfalova/" },
// { url: "https://www.instagram.com/rondesignlab/" },
// { url: "https://www.instagram.com/webinsane/" },
// { url: "https://www.instagram.com/mirohq/" },
// { url: "https://www.instagram.com/gurovdesign/" },
// { url: "https://www.instagram.com/tino.agency/" },
// { url: "https://www.instagram.com/artboardstudio/" },
// { url: "https://www.instagram.com/robinbobina.ru/" },
// { url: "https://www.instagram.com/refokusagency/" },
// { url: "https://www.instagram.com/qream.design/" },
// { url: "https://www.instagram.com/designbymix/" },
// { url: "https://www.instagram.com/videinfra_com/" },
// { url: "https://www.instagram.com/mentodesign.academy/" },
// { url: "https://www.instagram.com/deny.works/" },
// { url: "https://www.instagram.com/telidchenko/" },
// { url: "https://www.instagram.com/sayistudio/" },
// { url: "https://www.instagram.com/lstore_graphics/" },
// { url: "https://www.instagram.com/thomsoon_com/" },
// { url: "https://www.instagram.com/sliderrevolution/" },
// { url: "https://www.instagram.com/flashfamily.ru/" },
// { url: "https://www.instagram.com/ae.designpro/" },
// { url: "https://www.instagram.com/nolimcorp/" },
// { url: "https://www.instagram.com/margaritademshina/" },



// { url: "https://www.instagram.com/prosa.ai/" },
// { url: "https://www.instagram.com/dewaweb/" },
// { url: "https://www.instagram.com/prieds.tech/" },
// { url: "https://www.instagram.com/elitery.indo/" },
// { url: "https://www.instagram.com/midtransindonesia/" },
// { url: "https://www.instagram.com/digitalsolusi/" },
// { url: "https://www.instagram.com/multipolartechnology/" },
// { url: "https://www.instagram.com/atvcreative.asia/" },
// { url: "https://www.instagram.com/spesolution/" },
// { url: "https://www.instagram.com/qwordsdotcom/" },
// { url: "https://www.instagram.com/salt.indonesia/" },
// { url: "https://www.instagram.com/aksanity/" },
// { url: "https://www.instagram.com/toyotatrust_astra/" },
// { url: "https://www.instagram.com/sinau_koding/" },
// { url: "https://www.instagram.com/mediacloud_isp/" },
// { url: "https://www.instagram.com/id.seedbacklink/" },
// { url: "https://www.instagram.com/cyberacademyid/" },
// { url: "https://www.instagram.com/telkomsigma/" },
// { url: "https://www.instagram.com/codefest.id/" },
// { url: "https://www.instagram.com/searchdotagency/" },
// { url: "https://www.instagram.com/regtech.id/" },
// { url: "https://www.instagram.com/rumahwebgram/" },
// { url: "https://www.instagram.com/tanamduit.id/" },
// { url: "https://www.instagram.com/kotabi.id/" },
// { url: "https://www.instagram.com/idsdigitalcollege/" },
// { url: "https://www.instagram.com/idrumahcoding/" },
// { url: "https://www.instagram.com/onetwocode.id/" },
// { url: "https://www.instagram.com/xlaxiata_iot/" },
// { url: "https://www.instagram.com/niagahoster.id/" },
// { url: "https://www.instagram.com/xynexis/" },
// { url: "https://www.instagram.com/digitalic.id/" },
// { url: "https://www.instagram.com/eranyacloud/" },


// { url: "https://www.instagram.com/vishanjaliinfo/" },
// { url: "https://www.instagram.com/teckinfosolutions/" },
// { url: "https://www.instagram.com/makewebbetter/" },
// { url: "https://www.instagram.com/brandclever.in/" },
// { url: "https://www.instagram.com/xovient/" },
// { url: "https://www.instagram.com/appsrhino/" },
// { url: "https://www.instagram.com/itinfonity/" },
// { url: "https://www.instagram.com/prologictechnologies/" },
// { url: "https://www.instagram.com/netsmartz_llc/" },
// { url: "https://www.instagram.com/superiormarketingwebsitedesign/" },


// { url: "https://www.instagram.com/aisensy_official/" },
// { url: "https://www.instagram.com/zoopupindia/" },
// { url: "https://www.instagram.com/confluent_inc/" },
// { url: "https://www.instagram.com/iqfulfillment/" },
// { url: "https://www.instagram.com/dhanguarduae/" },
// { url: "https://www.instagram.com/techjockey_/" },
// { url: "https://www.instagram.com/ahrefs/" },
// { url: "https://www.instagram.com/logarithmics.us/" },
// { url: "https://www.instagram.com/brained.app/" },
// { url: "https://www.instagram.com/converta.ai/" },
// { url: "https://www.instagram.com/sendpulse/" },
// { url: "https://www.instagram.com/ondc_official/" },
// { url: "https://www.instagram.com/10web.io/" },
// { url: "https://www.instagram.com/mediaproav/" },
// { url: "https://www.instagram.com/redisinc/" },
// { url: "https://www.instagram.com/tatanexarc/" },
// { url: "https://www.instagram.com/edgeverve_official/" },
// { url: "https://www.instagram.com/create.studio.official/" },
// { url: "https://www.instagram.com/explodingtopics/" },
// { url: "https://www.instagram.com/blackcoffee_media/" },
// { url: "https://www.instagram.com/businessonbot_/" },
// { url: "https://www.instagram.com/ans_commerce/" },
// { url: "https://www.instagram.com/dvelpai/" },
// { url: "https://www.instagram.com/durable.ai/" },
// { url: "https://www.instagram.com/zocketads/" },
// { url: "https://www.instagram.com/smartleadai/" },
// { url: "https://www.instagram.com/skydo_official/" },
// { url: "https://www.instagram.com/doolahq/" },
// { url: "https://www.instagram.com/softwaresuggest_ss/" },
// { url: "https://www.instagram.com/askdigitalrahul/" },
// { url: "https://www.instagram.com/dotpe_india/" },
// { url: "https://www.instagram.com/graphyapp/" },
// { url: "https://www.instagram.com/duosec/" },
// { url: "https://www.instagram.com/app.adyogi/" },
// { url: "https://www.instagram.com/bacancytechnology/" },
// { url: "https://www.instagram.com/youngurbanproject/" },
// { url: "https://www.instagram.com/firefliesai/" },
// { url: "https://www.instagram.com/digitalpooja__/" },
// { url: "https://www.instagram.com/neuralcoder.ai/" },


// { url: "https://www.instagram.com/oraclecloudworld/" },
// { url: "https://www.instagram.com/internetofthings/" },
// { url: "https://www.instagram.com/cisco_community/" },
// { url: "https://www.instagram.com/azurecloudcompute/" },
// { url: "https://www.instagram.com/accentureus/" },
// { url: "https://www.instagram.com/sassoftware/" },
// { url: "https://www.instagram.com/zscalerinc/" },
// { url: "https://www.instagram.com/automation_anywhere/" },
// { url: "https://www.instagram.com/slackhq/" },
// { url: "https://www.instagram.com/salesforcejobs/" },
// { url: "https://www.instagram.com/data.chatter/" },
// { url: "https://www.instagram.com/hashicorp/" },
// { url: "https://www.instagram.com/splunk/" },
// { url: "https://www.instagram.com/hashicorplive/" },
// { url: "https://www.instagram.com/salesforce_hub/" },
// { url: "https://www.instagram.com/microsoftazurecloud/" },
// { url: "https://www.instagram.com/lifeatmcafee/" },
// { url: "https://www.instagram.com/servicenow_touchpoint/" },
// { url: "https://www.instagram.com/marketingcloud/" },
// { url: "https://www.instagram.com/thedigitalocean/" },
// { url: "https://www.instagram.com/discoverentrust/" },
// { url: "https://www.instagram.com/commvault/" },
// { url: "https://www.instagram.com/workatohq/" },
// { url: "https://www.instagram.com/delltechcareers/" },
// { url: "https://www.instagram.com/citrix/" },
// { url: "https://www.instagram.com/bigcommerce/" },
// { url: "https://www.instagram.com/the_devops_engineer/" },
// { url: "https://www.instagram.com/proofpoint/" },
// { url: "https://www.instagram.com/servicenow/" },
// { url: "https://www.instagram.com/appdynamics/" },
// { url: "https://www.instagram.com/datascience.journal/" },
// { url: "https://www.instagram.com/salesforcefr/" },
// { url: "https://www.instagram.com/salesforcedach/" },
// { url: "https://www.instagram.com/neo4j/" },
// { url: "https://www.instagram.com/learn_dataengineering/" },
// { url: "https://www.instagram.com/salesforceca/" },
// { url: "https://www.instagram.com/twilio/" },

];

// Function to insert seed data
const seedDB = async () => {
  try {
    await Link.deleteMany({}); // Clear existing data
    await Link.insertMany(seedData); // Insert new data
    console.log("Database seeded successfully");
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    mongoose.connection.close(); // Close the connection after seeding
  }
};

seedDB();
