require("dotenv").config();
const mongoose = require("mongoose");
const Link = require("./models/Link");

// Connect to the database
mongoose
  .connect(process.env.MONGO_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => console.log("Database connected"))
  .catch((err) => console.error("Database connection error:", err));

// Example data to seed the `Link` collection
const seedData = [

  
// { "url": "https://www.instagram.com/luida.sg/" },
// { "url": "https://www.instagram.com/redcupmedia.sg/" },
// { "url": "https://www.instagram.com/gemxtra/" },
// { "url": "https://www.instagram.com/simplyfi.co/" },
// { "url": "https://www.instagram.com/samson.ngai/" },
// { "url": "https://www.instagram.com/mavic.ai/" },
// { "url": "https://www.instagram.com/findyour.superpower/" },
// { "url": "https://www.instagram.com/72event/" },
// { "url": "https://www.instagram.com/vanguardcollege_sg/" },
// { "url": "https://www.instagram.com/workcentral.sg/" },
// { "url": "https://www.instagram.com/finnzcapital/" },
// { "url": "https://www.instagram.com/onekiramedia/" },
// { "url": "https://www.instagram.com/cashflowfixer/" },
// { "url": "https://www.instagram.com/ypphoto.graphy.official/" },
// { "url": "https://www.instagram.com/iconzwebs/" },
// { "url": "https://www.instagram.com/gu.jun.hui_official/" },
// { "url": "https://www.instagram.com/hisevendm/" },
// { "url": "https://www.instagram.com/wemarkysolutions/" },
// { "url": "https://www.instagram.com/mooreslore/" },
// { "url": "https://www.instagram.com/vktransformation/" },
// { "url": "https://www.instagram.com/beliveintl/" },
// { "url": "https://www.instagram.com/solutionsforasia/" },
// { "url": "https://www.instagram.com/blackstoneconsultancysarawak/" },
// { "url": "https://www.instagram.com/thebetteringlives/" },
// { "url": "https://www.instagram.com/atdsolution/" },

// { "url": "https://www.instagram.com/poarta9.ro/" },
// { "url": "https://www.instagram.com/canopyro/" },
// { "url": "https://www.instagram.com/north.store.ro/" },
// { "url": "https://www.instagram.com/solo_fintech/" },
// { "url": "https://www.instagram.com/relevo.agency/" },
// { "url": "https://www.instagram.com/postit.advertising/" },
// { "url": "https://www.instagram.com/curiera.transport/" },
// { "url": "https://www.instagram.com/digitalstar.ro/" },
// { "url": "https://www.instagram.com/rocketagencyro/" },
// { "url": "https://www.instagram.com/seedagency.ro/" },
// { "url": "https://www.instagram.com/thebasicfundamentals/" },
// { "url": "https://www.instagram.com/cristinaeros.youplus/" },
// { "url": "https://www.instagram.com/cezara_malancus/" },
// { "url": "https://www.instagram.com/actsipoliton/" },
// { "url": "https://www.instagram.com/psylife.ro/" },
// { "url": "https://www.instagram.com/socialpediaro/" },
// { "url": "https://www.instagram.com/biancapicu.ro/" },
// { "url": "https://www.instagram.com/coders_lab_romania/" },
// { "url": "https://www.instagram.com/brifadsmarketing/" },
// { "url": "https://www.instagram.com/simonacrisan18/" },
// { "url": "https://www.instagram.com/ionelaraducanu.psiholog/" },
// { "url": "https://www.instagram.com/emavidicanpsihoterapeut/" },
// { "url": "https://www.instagram.com/criss.digitalstory/" },
// { "url": "https://www.instagram.com/crenganis.geanina/" },
// { "url": "https://www.instagram.com/themarkers.ro/" },
// { "url": "https://www.instagram.com/cristina.otel/" },
// { "url": "https://www.instagram.com/psih.cristian.butan/" },
// { "url": "https://www.instagram.com/pauzadebine/" },
// { "url": "https://www.instagram.com/trudaio/" },
// { "url": "https://www.instagram.com/ioana.predoiuhub.ro/" },
// { "url": "https://www.instagram.com/iamorganizable.ro/" },
// { "url": "https://www.instagram.com/psihologadrianaprundaru/" },
// { "url": "https://www.instagram.com/interapie.reginamaria/" },
// { "url": "https://www.instagram.com/tipuritoxice/" },
// { "url": "https://www.instagram.com/edukiwi.ro/" },
// { "url": "https://www.instagram.com/ecommasters.digital/" },
// { "url": "https://www.instagram.com/magnoliadamian_/" },
// { "url": "https://www.instagram.com/banometru/" },
// { "url": "https://www.instagram.com/biciuscamedia/" },
// { "url": "https://www.instagram.com/themaineredhead" },
// { "url": "https://www.instagram.com/ashleighamarketing" },
// { "url": "https://www.instagram.com/digiflyagency" },
// { "url": "https://www.instagram.com/assistheragency" },
// { "url": "https://www.instagram.com/planbtelevision" },
// { "url": "https://www.instagram.com/vistasocialapp" },
// { "url": "https://www.instagram.com/lydiasmedia" },

// Mine 

{ "url": "https://www.instagram.com/accent_countertops/" },
{ "url": "https://www.instagram.com/alairhomes.aurora.newmarket/" },
{ "url": "https://www.instagram.com/adlgraniteandmarble/" },
{ "url": "https://www.instagram.com/alphacountertops/" },
{ "url": "https://www.instagram.com/ashleighamarketing/" },
{ "url": "https://www.instagram.com/ashleywebbinteriors/" },
{ "url": "https://www.instagram.com/ateliersjacob/" },
{ "url": "https://www.instagram.com/barleywood_kitchens/" },
{ "url": "https://www.instagram.com/batche11ermonkhouse/" },
{ "url": "https://www.instagram.com/bauteam_ny/" },
{ "url": "https://www.instagram.com/bexsonhomes/" },
{ "url": "https://www.instagram.com/beyondcustomcontractinginc/" },
{ "url": "https://www.instagram.com/bigfootcabinet/" },
{ "url": "https://www.instagram.com/blueheronsignaturehomes/" },
{ "url": "https://www.instagram.com/bob_goess_contracting/" },
{ "url": "https://www.instagram.com/bostonbuildingresources/" },
{ "url": "https://www.instagram.com/braamscustomcabinets/" },
{ "url": "https://www.instagram.com/brisbaneappliancesales/" },
{ "url": "https://www.instagram.com/studio.builtenvironment/" },
{ "url": "https://www.instagram.com/bunganotlow/" },
{ "url": "https://www.instagram.com/homeinharwinton/" },
{ "url": "https://www.instagram.com/georgianrenolife/" },
{ "url": "https://www.instagram.com/deborahclaire_interiors/" },
{ "url": "https://www.instagram.com/designwellinteriors/" },
{ "url": "https://www.instagram.com/eadonstonekitchens/" },
{ "url": "https://www.instagram.com/kutchenhaus__eltham_bexley/" },
{ "url": "https://www.instagram.com/figura_uk/" },
{ "url": "https://www.instagram.com/frontal_kitchens/" },
{ "url": "https://www.instagram.com/gdhomedesigns/" },
{ "url": "https://www.instagram.com/gallaghercollc/" },
{ "url": "https://www.instagram.com/galliardhomes/" },
{ "url": "https://www.instagram.com/gilbertandburke/" },
{ "url": "https://www.instagram.com/glennwoodcustombuilders/" },
{ "url": "https://www.instagram.com/hdrremodeling/" },
{ "url": "https://www.instagram.com/hira_construction/" },
{ "url": "https://www.instagram.com/hollisdevelopments/" },
{ "url": "https://www.instagram.com/lemongroverealty/" },
{ "url": "https://www.instagram.com/zyongkiko_ng/" },
{ "url": "https://www.instagram.com/icmgeelong/" },
{ "url": "https://www.instagram.com/kanjuinteriors/" },
{ "url": "https://www.instagram.com/kitchenelegancepoole/" },
{ "url": "https://www.instagram.com/lpearsondesign/" },
{ "url": "https://www.instagram.com/lifetime.kitchens/" },
{ "url": "https://www.instagram.com/mayfair_worktops/" },
{ "url": "https://www.instagram.com/mcevoyandrowley/" },
{ "url": "https://www.instagram.com/mcmonaglemarble/" },
{ "url": "https://www.instagram.com/megleonardco/" },
{ "url": "https://www.instagram.com/mje_interiors/" },
{ "url": "https://www.instagram.com/moderndesignandremodeling/" },
{ "url": "https://www.instagram.com/mollellkitchens/" },
{ "url": "https://www.instagram.com/myfathersheart/" },
{ "url": "https://www.instagram.com/nolte_africa/" },
{ "url": "https://www.instagram.com/oldcitykitchens/" },
{ "url": "https://www.instagram.com/otisinteriors/" },
{ "url": "https://www.instagram.com/oak_development/" },
{ "url": "https://www.instagram.com/ramoscompanies/" },
{ "url": "https://www.instagram.com/regalbathandkitchens/" },
{ "url": "https://www.instagram.com/robinjohnsoninteriors/" },
{ "url": "https://www.instagram.com/secondnaturekitchens/" },
{ "url": "https://www.instagram.com/siematic.official/" },
{ "url": "https://www.instagram.com/sldprojects/" },
{ "url": "https://www.instagram.com/southernoakconstruction/" },
{ "url": "https://www.instagram.com/subzerowolfcoveshowroommd/" },
{ "url": "https://www.instagram.com/townsendconstructionsnq/" },
{ "url": "https://www.instagram.com/gallery_fitted_kitchens/" },
{ "url": "https://www.instagram.com/transformrenovations/" },
{ "url": "https://www.instagram.com/usadreamstone/" },
{ "url": "https://www.instagram.com/viknstones/" },
{ "url": "https://www.instagram.com/volunteer_building_services/" },
{ "url": "https://www.instagram.com/weichertft/" },
{ "url": "https://www.instagram.com/wlkitchenandhome/" },
{ "url": "https://www.instagram.com/fandlkitchens/" },
{ "url": "https://www.instagram.com/jrzconstruction_dfw/" },
{ "url": "https://www.instagram.com/alairhomes.northyork/" },
{ "url": "https://www.instagram.com/advance_plumbing/" },
{ "url": "https://www.instagram.com/1909kitchens/" },
{ "url": "https://www.instagram.com/angiestithdesigns/" },
{ "url": "https://www.instagram.com/bisonconstruction/" },
{ "url": "https://www.instagram.com/californiaskylineremodeling/" },
{ "url": "https://www.instagram.com/cerno_group/" },
{ "url": "https://www.instagram.com/dorosflooring/" },
{ "url": "https://www.instagram.com/elitekitchenandbathroom/" },
{ "url": "https://www.instagram.com/ene_builders_/" },
{ "url": "https://www.instagram.com/harvardhomes/" },
{ "url": "https://www.instagram.com/housestohomesuae/" },
{ "url": "https://www.instagram.com/keelcustomhomes/" },
{ "url": "https://www.instagram.com/kitchenkinguae/" },
{ "url": "https://www.instagram.com/kitchens.international/" },
{ "url": "https://www.instagram.com/laplanteconstruction/" },
{ "url": "https://www.instagram.com/lennardallas/" },
{ "url": "https://www.instagram.com/miamicreativeconstructions/" },
{ "url": "https://www.instagram.com/smc_construction_inc/" },
{ "url": "https://www.instagram.com/mkmhome_hull/" },
{ "url": "https://www.instagram.com/quartzco.ca/" },
{ "url": "https://www.instagram.com/sallymonterrosa/" },
{ "url": "https://www.instagram.com/s7k7e7k7k/" },
{ "url": "https://www.instagram.com/smartstoneaustralia/" },
{ "url": "https://www.instagram.com/bluepearl_granite/" },
{ "url": "https://www.instagram.com/officialcapsule/" },
{ "url": "https://www.instagram.com/thecooleycartergroup/" },
{ "url": "https://www.instagram.com/thecuenyteam/" },
{ "url": "https://www.instagram.com/vita.marble/" },
{ "url": "https://www.instagram.com/highcottonhomes/" },
{ "url": "https://www.instagram.com/wsdesignbuild/" },
{ "url": "https://www.instagram.com/aaaffordablehome/" },
{ "url": "https://www.instagram.com/atop_manalapan_nj/" },
{ "url": "https://www.instagram.com/aclremodeling/" },
{ "url": "https://www.instagram.com/agsi_carpentry/" },
{ "url": "https://www.instagram.com/albritishstone/" },
{ "url": "https://www.instagram.com/allmarbletiles/" },
{ "url": "https://www.instagram.com/ajoyarchitects/" },
{ "url": "https://www.instagram.com/alohaairconditioningandheating/" },
{ "url": "https://www.instagram.com/atkinandthyme/" },
{ "url": "https://www.instagram.com/aandvmodernbathrooms/" },
{ "url": "https://www.instagram.com/balding_design_build/" },
{ "url": "https://www.instagram.com/bascoshowerdoors/" },
{ "url": "https://www.instagram.com/berensonhardware/" },
{ "url": "https://www.instagram.com/beroliconstruction/" },
{ "url": "https://www.instagram.com/bespokeglazingsolutions/" },
{ "url": "https://www.instagram.com/blackdiamondlandscape/" },
{ "url": "https://www.instagram.com/blacklinerenovations/" },
{ "url": "https://www.instagram.com/blindsterdotcom/" },
{ "url": "https://www.instagram.com/bobscarpetandfloors/" },
{ "url": "https://www.instagram.com/bradsellcontracting/" },
{ "url": "https://www.instagram.com//" },
{ "url": "https://www.instagram.com/builderstradingco/" },
{ "url": "https://www.instagram.com/buyrailings101/" },
{ "url": "https://www.instagram.com/castlebespokeflooring/" },
{ "url": "https://www.instagram.com/charleslintonconstruction/" },
{ "url": "https://www.instagram.com//" },
{ "url": "https://www.instagram.com/corona_hardwood_/" },
{ "url": "https://www.instagram.com/cbp_ltd/" },
{ "url": "https://www.instagram.com/cozyhomepros/" },
{ "url": "https://www.instagram.com/creative_design_build/" },
{ "url": "https://www.instagram.com/cutmy.uk/" },
{ "url": "https://www.instagram.com/decksdirect/" },
{ "url": "https://www.instagram.com/dacgllc/" },
{ "url": "https://www.instagram.com/demandconstruction/" },
{ "url": "https://www.instagram.com/digiorgiinc/" },
{ "url": "https://www.instagram.com/dornbrookconcretecoatings/" },
{ "url": "https://www.instagram.com/euro_construction_group/" },
{ "url": "https://www.instagram.com/croft_house_extension/" },
{ "url": "https://www.instagram.com/eldoradostone/" },
{ "url": "https://www.instagram.com/elgarkitchens/" },
{ "url": "https://www.instagram.com/epilaybuildingproducts/" },
{ "url": "https://www.instagram.com/erbs.ltd/" },
{ "url": "https://www.instagram.com/eriksfantasticflooring/" },
{ "url": "https://www.instagram.com/evergreenpowerukltd/" },
{ "url": "https://www.instagram.com/fab.build.pro/" },
{ "url": "https://www.instagram.com/featureinteriors/" },
{ "url": "https://www.instagram.com/finaltouchbakersfield/" },
{ "url": "https://www.instagram.com/floorshieldhouston/" },
{ "url": "https://www.instagram.com/the_fram_house/" },
{ "url": "https://www.instagram.com/frontline_construction1/" },
{ "url": "https://www.instagram.com/ga.granite/" },
{ "url": "https://www.instagram.com/garageexperts_official/" },
{ "url": "https://www.instagram.com/genesishomeimprovements/" },
{ "url": "https://www.instagram.com/genevaflooring1/" },
{ "url": "https://www.instagram.com/garoofadvisors/" },
{ "url": "https://www.instagram.com/gorrocinoroofing/" },
{ "url": "https://www.instagram.com/grandentrydoors/" },
{ "url": "https://www.instagram.com/gromanwindowsanddoors/" },
{ "url": "https://www.instagram.com/greenmtnbuilders/" },
{ "url": "https://www.instagram.com/grimesflooring/" },
{ "url": "https://www.instagram.com/buffalorestore/" },
{ "url": "https://www.instagram.com/tempe_restore/" },
{ "url": "https://www.instagram.com/harmonytimberworks/" },
{ "url": "https://www.instagram.com/homeinnovationkb/" },
{ "url": "https://www.instagram.com/home.servicesplus/" },
{ "url": "https://www.instagram.com/homesteadstructures/" },
{ "url": "https://www.instagram.com/homestylewindows/" },
{ "url": "https://www.instagram.com/hullypods/" },
{ "url": "https://www.instagram.com/huphome/" },
{ "url": "https://www.instagram.com/inspiredclosetschicago/" },
{ "url": "https://www.instagram.com/_jr_ps/" },
{ "url": "https://www.instagram.com/jcconstruction.us/" },
{ "url": "https://www.instagram.com/buildersjpt/" },
{ "url": "https://www.instagram.com/jv_blinds/" },
{ "url": "https://www.instagram.com/kairos.roofing/" },
{ "url": "https://www.instagram.com/kcakitchens/" },
{ "url": "https://www.instagram.com/kcbr_design_remodel/" },
{ "url": "https://www.instagram.com/kitchenandbathshop/" },
{ "url": "https://www.instagram.com/kvc.constructions/" },
{ "url": "https://www.instagram.com/larry_isufi_construction.inc/" },
{ "url": "https://www.instagram.com/leonorconstruction.ma/" },
{ "url": "https://www.instagram.com/level5pntgllc/" },
{ "url": "https://www.instagram.com/lt.flooring/" },
{ "url": "https://www.instagram.com/wetroomsonline/" },
{ "url": "https://www.instagram.com/magnoliahrg/" },
{ "url": "https://www.instagram.com/maisonconstructionandroofing/" },
{ "url": "https://www.instagram.com/warmerhomeimprovements/" },
{ "url": "https://www.instagram.com/manidesignandbuild/" },
{ "url": "https://www.instagram.com/memphisgarageandclosets/" },
{ "url": "https://www.instagram.com/metal.roofing/" },
{ "url": "https://www.instagram.com/newprohome/" },
{ "url": "https://www.instagram.com/northlondongardens/" },
{ "url": "https://www.instagram.com/exploreremodeling/" },
{ "url": "https://www.instagram.com/oakfieldbeams/" },
{ "url": "https://www.instagram.com/onehourheatair/" },
{ "url": "https://www.instagram.com/opticupvcwindows/" },
{ "url": "https://www.instagram.com/orangellamaltd/" },
{ "url": "https://www.instagram.com/painted_bespoke_joinery/" },
{ "url": "https://www.instagram.com/paparonenewhomes/" },
{ "url": "https://www.instagram.com/platinumseamlessgutters/" },
{ "url": "https://www.instagram.com/thepodhousecompany/" },
{ "url": "https://www.instagram.com/precisiongarage.fc/" },
{ "url": "https://www.instagram.com/primework.construction/" },
{ "url": "https://www.instagram.com/primocarpentry/" },
{ "url": "https://www.instagram.com/pro_performance_construction/" },
{ "url": "https://www.instagram.com/prolineflooringaz/" },
{ "url": "https://www.instagram.com/pronormusa/" },
{ "url": "https://www.instagram.com/proofvision/" },
{ "url": "https://www.instagram.com/rb.restorationbuilders/" },
{ "url": "https://www.instagram.com/rbuildersdevelopers/" },
{ "url": "https://www.instagram.com/regis_plastering/" },
{ "url": "https://www.instagram.com/remodelingright/" },
{ "url": "https://www.instagram.com/restoreandrefresh.uk/" },
{ "url": "https://www.instagram.com/rjd_construction/" },
{ "url": "https://www.instagram.com/ross_clarkroofing/" },
{ "url": "https://www.instagram.com/ryanandsonsconstruction/" },
{ "url": "https://www.instagram.com/sdshomesconstruction/" },
{ "url": "https://www.instagram.com/selecthomeimprovements/" },
{ "url": "https://www.instagram.com/shugarmansbath/" },
{ "url": "https://www.instagram.com/sjpoolsnj/" },
{ "url": "https://www.instagram.com/smartgranitelv/" },
{ "url": "https://www.instagram.com/southernluxuryhomes/" },
{ "url": "https://www.instagram.com/southern_maine_remodeling/" },
{ "url": "https://www.instagram.com/spfscreensandawnings/" },
{ "url": "https://www.instagram.com/straightlinedesignkitchens/" },
{ "url": "https://www.instagram.com/sunnyfieldscabinetry/" },
{ "url": "https://www.instagram.com/tabordesignbuild/" },
{ "url": "https://www.instagram.com/tdgfloors/" },
{ "url": "https://www.instagram.com/thetrustyhandyman/" },
{ "url": "https://www.instagram.com/timothy_parks_construction/" },
{ "url": "https://www.instagram.com/toro_construction_woburn/" },
{ "url": "https://www.instagram.com/tranquilgardenroomsltd/" },
{ "url": "https://www.instagram.com/triple_state_construction/" },
{ "url": "https://www.instagram.com/universalappliance/" },
{ "url": "https://www.instagram.com/uakcstudiocity/" },
{ "url": "https://www.instagram.com/venepaintinginc/" },
{ "url": "https://www.instagram.com/vestaconstructionltd/" },
{ "url": "https://www.instagram.com/vinnovadesign/" },
{ "url": "https://www.instagram.com/wallauerdesign/" },
{ "url": "https://www.instagram.com/waysource/" },
{ "url": "https://www.instagram.com/weloveyourprojects/" },
{ "url": "https://www.instagram.com/westlakeroyalroofing/" },
{ "url": "https://www.instagram.com/wickes/" },
{ "url": "https://www.instagram.com/windowworld/" },
{ "url": "https://www.instagram.com/spiralcellars/" },
{ "url": "https://www.instagram.com/wisebuildersca/" },
{ "url": "https://www.instagram.com/yankeehomeimprovement/" },
{ "url": "https://www.instagram.com/ykbstoremiami/" },
{ "url": "https://www.instagram.com/youngideasconstruction/" },
{ "url": "https://www.instagram.com/yourhomeimprovementco/" },
{ "url": "https://www.instagram.com/jaycohandyman/" },
{ "url": "https://www.instagram.com/ammelconstruction/" },
{ "url": "https://www.instagram.com/atticareusa/" },
{ "url": "https://www.instagram.com/basement_remodeling_com/" },
{ "url": "https://www.instagram.com/champion_drywall_ma/" },
{ "url": "https://www.instagram.com/cefofthesouthinc/" },
{ "url": "https://www.instagram.com/d.f.construction/" },
{ "url": "https://www.instagram.com/thednrbros/" },
{ "url": "https://www.instagram.com/everlogs/" },
{ "url": "https://www.instagram.com/extremewoodwork/" },
{ "url": "https://www.instagram.com/fb_doors/" },
{ "url": "https://www.instagram.com/flat_roofing_systems/" },
{ "url": "https://www.instagram.com/harmonydbc/" },
{ "url": "https://www.instagram.com/hellingsbuildersinc/" },
{ "url": "https://www.instagram.com/hunterbuildingservicesltd/" },
{ "url": "https://www.instagram.com/lifetimehomeremodeling/" },
{ "url": "https://www.instagram.com/mandafences/" },
{ "url": "https://www.instagram.com/masterstouchdesignbuild/" },
{ "url": "https://www.instagram.com/northwestfires/" },
{ "url": "https://www.instagram.com/outlinegci/" },
{ "url": "https://www.instagram.com/designs4youremodeling/" },
{ "url": "https://www.instagram.com/thecarpenterhandyman/" },
{ "url": "https://www.instagram.com/sourcesfordesign/" },
{ "url": "https://www.instagram.com/thebathauthority/" },
{ "url": "https://www.instagram.com/nuprojects.co/" },
{ "url": "https://www.instagram.com/360coatingsolutions/" },
{ "url": "https://www.instagram.com/3flo_bathrooms/" },
{ "url": "https://www.instagram.com/a1_contractors_inc/" },
{ "url": "https://www.instagram.com/ajwellsroofing/" },
{ "url": "https://www.instagram.com/ar_homeconstructionllc/" },
{ "url": "https://www.instagram.com/a2z.builders.colorado/" },
{ "url": "https://www.instagram.com/aaiflooring/" },
{ "url": "https://www.instagram.com/adlgraniteandmarble/" },
{ "url": "https://www.instagram.com/ahhomeimprovements/" },
{ "url": "https://www.instagram.com/ajthomeimprovements/" },
{ "url": "https://www.instagram.com/allcounty_millworks/" },
{ "url": "https://www.instagram.com/allseasonsroofingrestoration/" },
{ "url": "https://www.instagram.com/allevaconstruction/" },
{ "url": "https://www.instagram.com/almar_building/" },
{ "url": "https://www.instagram.com/alphaprotools/" },
{ "url": "https://www.instagram.com/alside_buildingproducts/" },
{ "url": "https://www.instagram.com/alueliteinternaldoors/" },
{ "url": "https://www.instagram.com/aluco.uk/" },
{ "url": "https://www.instagram.com/anawhiteplans/" },
{ "url": "https://www.instagram.com/anewkb/" },
{ "url": "https://www.instagram.com/cap_metal_roofing/" },
{ "url": "https://www.instagram.com/anthonywilderdesignbuild/" },
{ "url": "https://www.instagram.com/arkofloors/" },
{ "url": "https://www.instagram.com/arnoldpropertyinspections1/" },
{ "url": "https://www.instagram.com/bathroom_review/" },
{ "url": "https://www.instagram.com/bathroomsupastore/" },
{ "url": "https://www.instagram.com/bayhomeimprovements/" },
{ "url": "https://www.instagram.com/bbswindowsolutions/" },
{ "url": "https://www.instagram.com/beamstobasements/" },
{ "url": "https://www.instagram.com/beaulieuandsonshomeimprovement/" },
{ "url": "https://www.instagram.com/coathamhouserenovation/" },
{ "url": "https://www.instagram.com/benchmarkloftsltd/" },
{ "url": "https://www.instagram.com/berkeleyexteriors/" },
{ "url": "https://www.instagram.com/bespokelandscapingprojectsltd/" },
{ "url": "https://www.instagram.com/bespoketimbercreations/" },
{ "url": "https://www.instagram.com/bestpricekitchenbath/" },
{ "url": "https://www.instagram.com/bhcpropertysolutions/" },
{ "url": "https://www.instagram.com/bigdogconstructionnj/" },
{ "url": "https://www.instagram.com/blessed_design_construction/" },
{ "url": "https://www.instagram.com/bozettis/" },
{ "url": "https://www.instagram.com/bryantelectrical/" },
{ "url": "https://www.instagram.com/builditmagazine/" },
{ "url": "https://www.instagram.com/bygonesashwindows/" },
{ "url": "https://www.instagram.com/ckroofinginc/" },
{ "url": "https://www.instagram.com/cacindustriesinc/" },
{ "url": "https://www.instagram.com/californiaturf_puttinggreens/" },
{ "url": "https://www.instagram.com/canterconstruction/" },
{ "url": "https://www.instagram.com/carefreehomesinc/" },
{ "url": "https://www.instagram.com/cascadecustomhomesanddesign/" },
{ "url": "https://www.instagram.com/cavalieriflooring/" },
{ "url": "https://www.instagram.com/champion_projects/" },
{ "url": "https://www.instagram.com/cobexcg/" },
{ "url": "https://www.instagram.com/cognitiveconstruction/" },
{ "url": "https://www.instagram.com/colectivocreative/" },
{ "url": "https://www.instagram.com/clpmconstructionconsultancy/" },
{ "url": "https://www.instagram.com/probuilders_nyc/" },
{ "url": "https://www.instagram.com/rocco_solutions/" },
{ "url": "https://www.instagram.com/continentalhomegroup/" },
{ "url": "https://www.instagram.com/cornerstone__contracting/" },
{ "url": "https://www.instagram.com/cornishtraders/" },
{ "url": "https://www.instagram.com/creatingspacesgroup/" },
{ "url": "https://www.instagram.com/creativepaintconcepts/" },
{ "url": "https://www.instagram.com/crkwindows/" },
{ "url": "https://www.instagram.com/turnerhomect/" },
{ "url": "https://www.instagram.com/casamiadesignbuildco/" },
{ "url": "https://www.instagram.com/dcassaofficial/" },
{ "url": "https://www.instagram.com/dabella_exteriors/" },
{ "url": "https://www.instagram.com/breslowdesign/" },
{ "url": "https://www.instagram.com/dancoinc/" },
{ "url": "https://www.instagram.com/daviddugglebyauctioneers/" },
{ "url": "https://www.instagram.com/diazchemical/" },
{ "url": "https://www.instagram.com/designfirstbuilders/" },
{ "url": "https://www.instagram.com/dspacestv/" },
{ "url": "https://www.instagram.com/starwooddistributors/" },
{ "url": "https://www.instagram.com/diamondpeakhomes/" },
{ "url": "https://www.instagram.com/doctorspainting/" },
{ "url": "https://www.instagram.com/doorsuppliesonline/" },
{ "url": "https://www.instagram.com/dortechdoors/" },
{ "url": "https://www.instagram.com/dream_custom_kitchens/" },
{ "url": "https://www.instagram.com/drywall.masters/" },
{ "url": "https://www.instagram.com/duragarages/" },
{ "url": "https://www.instagram.com/ehrbuildingsupply/" },
{ "url": "https://www.instagram.com/ecohomebuildersinc/" },
{ "url": "https://www.instagram.com/ecotrus_/" },
{ "url": "https://www.instagram.com/remodelingnetworkllc/" },
{ "url": "https://www.instagram.com/eg_evertonglass/" },
{ "url": "https://www.instagram.com/ejallcontractors/" },
{ "url": "https://www.instagram.com/kitchensbyemma/" },
{ "url": "https://www.instagram.com/ephraimremodeling/" },
{ "url": "https://www.instagram.com/epicroofreplacement/" },
{ "url": "https://www.instagram.com/evenmadetrade/" },
{ "url": "https://www.instagram.com/green.valleycorp/" },
{ "url": "https://www.instagram.com/fhiaremodeling/" },
{ "url": "https://www.instagram.com/firstimpressionironworks/" },
{ "url": "https://www.instagram.com/fiveseasonswindows/" },
{ "url": "https://www.instagram.com/floor_angels/" },
{ "url": "https://www.instagram.com/scflooringmasters/" },
{ "url": "https://www.instagram.com/floorstoyourdoor_fremont/" },
{ "url": "https://www.instagram.com/floridaimpactwindowsanddoors/" },
{ "url": "https://www.instagram.com/fludescarpets/" },
{ "url": "https://www.instagram.com/thefoamboys/" },
{ "url": "https://www.instagram.com/freestylekitchens_bedrooms/" },
{ "url": "https://www.instagram.com/gfedaleroof/" },
{ "url": "https://www.instagram.com/garageexpertsjax/" },
{ "url": "https://www.instagram.com/garagefloorin24/" },
{ "url": "https://www.instagram.com/garagelivingconnecticut/" },
{ "url": "https://www.instagram.com/garagelivingnj/" },
{ "url": "https://www.instagram.com/gentekcanada/" },
{ "url": "https://www.instagram.com/glassblockwarehouse/" },
{ "url": "https://www.instagram.com/goaduca/" },
{ "url": "https://www.instagram.com/thegorillabrothers/" },
{ "url": "https://www.instagram.com/grainbespoke/" },
{ "url": "https://www.instagram.com/green___innovations/" },
{ "url": "https://www.instagram.com/greenribbonconstruction/" },
{ "url": "https://www.instagram.com/greenoakconceptanddesign/" },
{ "url": "https://www.instagram.com/griffwerk_usa/" },
{ "url": "https://www.instagram.com/h2m_epoxy_floors/" },
{ "url": "https://www.instagram.com/hpm_plumbing_bathrooms/" },
{ "url": "https://www.instagram.com/hampton_group/" },
{ "url": "https://www.instagram.com/handymaestro/" },
{ "url": "https://www.instagram.com/hangitservices/" },
{ "url": "https://www.instagram.com/the.harveyhome/" },
{ "url": "https://www.instagram.com/hardwarexsupply/" },
{ "url": "https://www.instagram.com/hartts/" },
{ "url": "https://www.instagram.com/hattinkhomesinteriors/" },
{ "url": "https://www.instagram.com/hawkstoneluxuryhomes/" },
{ "url": "https://www.instagram.com/haywardpoolproducts/" },
{ "url": "https://www.instagram.com/hellogarageus/" },
{ "url": "https://www.instagram.com/hey.pros/" },
{ "url": "https://www.instagram.com/hippo.products/" },
{ "url": "https://www.instagram.com/homearttile/" },
{ "url": "https://www.instagram.com/homelogicuk/" },
{ "url": "https://www.instagram.com/hometelligent/" },
{ "url": "https://www.instagram.com/horizondesigncenter/" },
{ "url": "https://www.instagram.com/houseworksinc/" },
{ "url": "https://www.instagram.com/wearehowarth/" },
{ "url": "https://www.instagram.com/i2create.us/" },
{ "url": "https://www.instagram.com/iberiatiles/" },
{ "url": "https://www.instagram.com/iloftconversions/" },
{ "url": "https://www.instagram.com/ins_coat/" },
{ "url": "https://www.instagram.com/intotheblueroofing/" },
{ "url": "https://www.instagram.com/irenovatebuildingsolutionsltd/" },
{ "url": "https://www.instagram.com/istoria_by_jordan_andrews/" },
{ "url": "https://www.instagram.com/iwanoconstruction/" },
{ "url": "https://www.instagram.com/jackandsonsmasonry/" },
{ "url": "https://www.instagram.com/jacuzziukspaandbath/" },
{ "url": "https://www.instagram.com/jblroofingandconstruction/" },
{ "url": "https://www.instagram.com/jcfloorsplus/" },
{ "url": "https://www.instagram.com/jennifergilmerkb/" },
{ "url": "https://www.instagram.com/jewel_windows/" },
{ "url": "https://www.instagram.com/jfwflooring/" },
{ "url": "https://www.instagram.com/joesconstructioncompany/" },
{ "url": "https://www.instagram.com/colorsbycreation/" },
{ "url": "https://www.instagram.com/jsproconstruction/" },
{ "url": "https://www.instagram.com/jsmconctruction_pools/" },
{ "url": "https://www.instagram.com/judges_building_services/" },
{ "url": "https://www.instagram.com/buildingprojectmanager/" },
{ "url": "https://www.instagram.com/junkhaulingexpress/" },
{ "url": "https://www.instagram.com/junkluggersofatlmetroeast/" },
{ "url": "https://www.instagram.com/jvrenovationanddesigns/" },
{ "url": "https://www.instagram.com/kmsheetmetal/" },
{ "url": "https://www.instagram.com/kabbadoor/" },
{ "url": "https://www.instagram.com/kaizenfurniture/" },
{ "url": "https://www.instagram.com/coloradokaylyn/" },
{ "url": "https://www.instagram.com/kb.solar.us/" },
{ "url": "https://www.instagram.com/kgtbuilders/" },
{ "url": "https://www.instagram.com/kitchenrefreshinc/" },
{ "url": "https://www.instagram.com/kitchenwarehouseltd/" },
{ "url": "https://www.instagram.com/knocketydoors/" },
{ "url": "https://www.instagram.com/lakeside_rd/" },
{ "url": "https://www.instagram.com/lakesidesurfacesinc/" },
{ "url": "https://www.instagram.com/leaffreehomeimprovements/" },
{ "url": "https://www.instagram.com/lucaspulakconstruction/" },
{ "url": "https://www.instagram.com/luxewalling/" },
{ "url": "https://www.instagram.com/m_cdeckcompany/" },
{ "url": "https://www.instagram.com/made2measure_interiors/" },
{ "url": "https://www.instagram.com/madefortrade4226/" },
{ "url": "https://www.instagram.com/maine_properties/" },
{ "url": "https://www.instagram.com/maingreenconstructionca/" },
{ "url": "https://www.instagram.com/mainstreetdesignbuild/" },
{ "url": "https://www.instagram.com/maisonhomeconstruction/" },
{ "url": "https://www.instagram.com/majorconstructioninc/" },
{ "url": "https://www.instagram.com/mangowoutdoor/" },
{ "url": "https://www.instagram.com/mariano_co/" },
{ "url": "https://www.instagram.com/minkremodeling/" },
{ "url": "https://www.instagram.com/mcsurfaces/" },
{ "url": "https://www.instagram.com/joseph_salvatore/" },
{ "url": "https://www.instagram.com/melarafencing/" },
{ "url": "https://www.instagram.com/housingmuse/" },
{ "url": "https://www.instagram.com/mbrg_llc/" },
{ "url": "https://www.instagram.com/meyerandsons/" },
{ "url": "https://www.instagram.com/macaw_coatings/" },
{ "url": "https://www.instagram.com/salvo_contracting_llc/" },
{ "url": "https://www.instagram.com/missiatodesignandbuild/" },
{ "url": "https://www.instagram.com/modafloors/" },
{ "url": "https://www.instagram.com/mommakdiy/" },
{ "url": "https://www.instagram.com/morenollc/" },
{ "url": "https://www.instagram.com/mrhandymancincoranch/" },
{ "url": "https://www.instagram.com/mrhandymanwheatonhinsdale/" },
{ "url": "https://www.instagram.com/munzconstruction/" },
{ "url": "https://www.instagram.com/mygarageandgates/" },
{ "url": "https://www.instagram.com/my.house.makeover/" },
{ "url": "https://www.instagram.com/mybuilder/" },
{ "url": "https://www.instagram.com/neilkellycompany/" },
{ "url": "https://www.instagram.com/nexgenrrfl/" },
{ "url": "https://www.instagram.com/nextleveladubuilders/" },
{ "url": "https://www.instagram.com/nextlevelconst.inc/" },
{ "url": "https://www.instagram.com/ngc_build/" },
{ "url": "https://www.instagram.com/buildnorthshore/" },
{ "url": "https://www.instagram.com/nostalgiaworksurfaces/" },
{ "url": "https://www.instagram.com/novoconstructionllc/" },
{ "url": "https://www.instagram.com/npc.concrete/" },
{ "url": "https://www.instagram.com/number_552/" },
{ "url": "https://www.instagram.com/onpoint_development_llc/" },
{ "url": "https://www.instagram.com/ookhardware/" },
{ "url": "https://www.instagram.com/opensquareglazing/" },
{ "url": "https://www.instagram.com/optimalestatesltd/" },
{ "url": "https://www.instagram.com/gands_proservices/" },
{ "url": "https://www.instagram.com/osullivan_building/" },
{ "url": "https://www.instagram.com/jocey_at_pjmasonry/" },
{ "url": "https://www.instagram.com/pactool_intl/" },
{ "url": "https://www.instagram.com/theparadigmhomes/" },
{ "url": "https://www.instagram.com/paragonstairs/" },
{ "url": "https://www.instagram.com/paramount_remodeling/" },
{ "url": "https://www.instagram.com/alicetchan/" },
{ "url": "https://www.instagram.com/androskitchens/" },
{ "url": "https://www.instagram.com/austinflipsters/" },
{ "url": "https://www.instagram.com/ayakitchens/" },
{ "url": "https://www.instagram.com/broadwaykitchens/" },
{ "url": "https://www.instagram.com/townbuildersconstruction/" },
{ "url": "https://www.instagram.com/buzz_ferrell/" },
{ "url": "https://www.instagram.com/cardwellbuilt/" },
{ "url": "https://www.instagram.com/ckccustomhomes/" },
{ "url": "https://www.instagram.com/knippcontracting/" },
{ "url": "https://www.instagram.com/creativekitchensredbanknj/" },
{ "url": "https://www.instagram.com/ctapplianceandfireplace/" },
{ "url": "https://www.instagram.com/synergyhomesflorida/" },
{ "url": "https://www.instagram.com/drhorton/" },
{ "url": "https://www.instagram.com/gordontjacob/" },
{ "url": "https://www.instagram.com/exoticcountertops/" },
{ "url": "https://www.instagram.com/fdproje/" },
{ "url": "https://www.instagram.com/farquharkitchens/" },
{ "url": "https://www.instagram.com/gjgardneraus/" },
{ "url": "https://www.instagram.com/gkcardiff/" },
{ "url": "https://www.instagram.com/hamilton_stern/" },
{ "url": "https://www.instagram.com/hoodshomecenter_foley/" },
{ "url": "https://www.instagram.com/jacksondevs/" },
{ "url": "https://www.instagram.com/jrowland777/" },
{ "url": "https://www.instagram.com/kaboodlekitchen/" },
{ "url": "https://www.instagram.com/elitekitchens/" },
{ "url": "https://www.instagram.com/kentwoodfloors/" },
{ "url": "https://www.instagram.com/kitchencraftdesignstudio/" },
{ "url": "https://www.instagram.com/kraftmaid/" },
{ "url": "https://www.instagram.com/kubekitchensuk/" },
{ "url": "https://www.instagram.com/lakehousestore/" },
{ "url": "https://www.instagram.com/leichttoronto/" },
{ "url": "https://www.instagram.com/lennarseflorida/" },
{ "url": "https://www.instagram.com/limedesigns7977/" },
{ "url": "https://www.instagram.com/lindsaydesigncentre/" },
{ "url": "https://www.instagram.com/ma.arquitectura/" },
{ "url": "https://www.instagram.com/marvelcabinetco/" },
{ "url": "https://www.instagram.com/marwynnconstruction/" },
{ "url": "https://www.instagram.com/mascotbespoke/" },
{ "url": "https://www.instagram.com/mcdonald_contracting/" },
{ "url": "https://www.instagram.com/meadrenovations/" },
{ "url": "https://www.instagram.com/meyerbrothersandsons78/" },
{ "url": "https://www.instagram.com/nardini_custom/" },
{ "url": "https://www.instagram.com/newlegacyhomestampa/" },
{ "url": "https://www.instagram.com/bradleydesignstudio/" },
{ "url": "https://www.instagram.com/paragonkitchens/" },
{ "url": "https://www.instagram.com/paula_nycdb/" },
{ "url": "https://www.instagram.com/interior_love_affair_/" },
{ "url": "https://www.instagram.com/reborncabinets/" },
{ "url": "https://www.instagram.com/rescabinetry/" },
{ "url": "https://www.instagram.com/revolvingrooms/" },
{ "url": "https://www.instagram.com/shoproyalflooring/" },
{ "url": "https://www.instagram.com/ryannreed.designbuild/" },
{ "url": "https://www.instagram.com/sdabuildlondon/" },
{ "url": "https://www.instagram.com/sheewaterhome/" },
{ "url": "https://www.instagram.com/showcasekitchennj/" },
{ "url": "https://www.instagram.com/siematicuae/" },
{ "url": "https://www.instagram.com/s_h_construction/" },
{ "url": "https://www.instagram.com/tzhomeimprovement/" },
{ "url": "https://www.instagram.com/taylorflooringdesigncentre/" },
{ "url": "https://www.instagram.com/homesolutionsbytaylorscot/" },
{ "url": "https://www.instagram.com/shoptenzo/" },
{ "url": "https://www.instagram.com/theplatinumhouse/" },
{ "url": "https://www.instagram.com/theremodelstudio/" },
{ "url": "https://www.instagram.com/venetohomes/" },
{ "url": "https://www.instagram.com/warehouseguys/" },
{ "url": "https://www.instagram.com/youngbrosinc/" },
{ "url": "https://www.instagram.com/lord_general_contractors/" },
{ "url": "https://www.instagram.com/akfittedinteriors/" },
{ "url": "https://www.instagram.com/labottega.birsin/" },
{ "url": "https://www.instagram.com/magnokitchens/" },
{ "url": "https://www.instagram.com/marklauren95/" },
{ "url": "https://www.instagram.com/marmivrech/" },
{ "url": "https://www.instagram.com/masonconstruction/" },
{ "url": "https://www.instagram.com/mchomeimprovements/" },
{ "url": "https://www.instagram.com/mdswim_tri_/" },
{ "url": "https://www.instagram.com/melinda_deckert_dfw_realtor/" },
{ "url": "https://www.instagram.com/nhancewoodrefinishing/" },
{ "url": "https://www.instagram.com/dynamic.space.inc/" },
{ "url": "https://www.instagram.com/new_start_kitchens/" },
{ "url": "https://www.instagram.com/oasishomeimprovement/" },
{ "url": "https://www.instagram.com/oikohome_s.a/" },
{ "url": "https://www.instagram.com/oncgranite/" },
{ "url": "https://www.instagram.com/ortegaremodeling/" },
{ "url": "https://www.instagram.com/palazzo_glasgow/" },
{ "url": "https://www.instagram.com/paulbarrykbb/" },
{ "url": "https://www.instagram.com/platinumfuturespainting/" },
{ "url": "https://www.instagram.com/rialto_flooring/" },
{ "url": "https://www.instagram.com/sherekitchens/" },
{ "url": "https://www.instagram.com/shoreandcountrykitchens/" },
{ "url": "https://www.instagram.com/skywalkerconstruction/" },
{ "url": "https://www.instagram.com/somrakinteriors/" },
{ "url": "https://www.instagram.com/squarecorner_designbuild/" },
{ "url": "https://www.instagram.com/stoneandearthltd/" },
{ "url": "https://www.instagram.com/stoneinteriorsgroup/" },
{ "url": "https://www.instagram.com/stoneworldlondon/" },
{ "url": "https://www.instagram.com/subzerowolfhk/" },
{ "url": "https://www.instagram.com/summitgroupbuildingcompany/" },
{ "url": "https://www.instagram.com/summithomesnz/" },
{ "url": "https://www.instagram.com/kitchenworksusa/" },
{ "url": "https://www.instagram.com/thelakeshomecentre/" },
{ "url": "https://www.instagram.com/tailoredclosetgreaterdc/" },
{ "url": "https://www.instagram.com/thorsonrestoration/" },
{ "url": "https://www.instagram.com/tiletoria/" },
{ "url": "https://www.instagram.com/tonymillerconstruction/" },
{ "url": "https://www.instagram.com/traditionhomegroup/" },
{ "url": "https://www.instagram.com/trouvehomeandlifestyle/" },
{ "url": "https://www.instagram.com/ultimodevelopment/" },
{ "url": "https://www.instagram.com/unique_custom_cabinets/" },
{ "url": "https://www.instagram.com/vancouvergc/" },
{ "url": "https://www.instagram.com/vias_houses/" },
{ "url": "https://www.instagram.com/virtuosobuilders/" },
{ "url": "https://www.instagram.com/waldorfcabinets/" },
{ "url": "https://www.instagram.com/crossingdc/" },
{ "url": "https://www.instagram.com/weekshardwoodflooring/" },
{ "url": "https://www.instagram.com/westbowhomes/" },
{ "url": "https://www.instagram.com/westland_homes/" },
{ "url": "https://www.instagram.com/younique_build/" },
{ "url": "https://www.instagram.com/tampadesignsbyjo/" },
{ "url": "https://www.instagram.com/discoveralair/" },
{ "url": "https://www.instagram.com/alairhomesreddeer/" },
{ "url": "https://www.instagram.com/alderidge_construction/" },
{ "url": "https://www.instagram.com/alfieandgeorgeuk/" },
{ "url": "https://www.instagram.com/ambiancecabinets/" },
{ "url": "https://www.instagram.com/amodoeuropeancollection/" },
{ "url": "https://www.instagram.com/andexkitchens/" },
{ "url": "https://www.instagram.com/arclineabarcelona/" },
{ "url": "https://www.instagram.com/arclineasg/" },
{ "url": "https://www.instagram.com/arthaus_bathroom_kitchen/" },
{ "url": "https://www.instagram.com/bathbespoke/" },
{ "url": "https://www.instagram.com/bauen_design_/" },
{ "url": "https://www.instagram.com/bohausdesign/" },
{ "url": "https://www.instagram.com/bristoltile/" },
{ "url": "https://www.instagram.com/casadomainecustomhomes/" },
{ "url": "https://www.instagram.com/3rdgenerationhomes/" },
{ "url": "https://www.instagram.com/sagehillcottage/" },
{ "url": "https://www.instagram.com/condoworks/" },
{ "url": "https://www.instagram.com/conor_whelan_fitted_furniture/" },
{ "url": "https://www.instagram.com/cornerstonekb/" },
{ "url": "https://www.instagram.com/countertopsolutiondfw/" },
{ "url": "https://www.instagram.com/crownkitchenssurrey/" },
{ "url": "https://www.instagram.com/cypressdesignco/" },
{ "url": "https://www.instagram.com/davidreidhomesaus/" },
{ "url": "https://www.instagram.com/day_true/" },
{ "url": "https://www.instagram.com/dellannova/" },
{ "url": "https://www.instagram.com/dcwhomedecor/" },
{ "url": "https://www.instagram.com/petoskeykitchens/" },
{ "url": "https://www.instagram.com/deslauriercustomcabinets/" },
{ "url": "https://www.instagram.com/donatellibuilders/" },
{ "url": "https://www.instagram.com/brendan_dunne.au/" },
{ "url": "https://www.instagram.com/edwardssmithconstruction/" },
{ "url": "https://www.instagram.com/eurodesignbuild/" },
{ "url": "https://www.instagram.com/fortebuildinggroup/" },
{ "url": "https://www.instagram.com/franklinbuilt_inc/" },
{ "url": "https://www.instagram.com/fusionhome_kitchen_bathroom/" },
{ "url": "https://www.instagram.com/greencedarhomes/" },
{ "url": "https://www.instagram.com/h1_constructionhawaii/" },
{ "url": "https://www.instagram.com/haledesign/" },
{ "url": "https://www.instagram.com/halotilesbathrooms/" },
{ "url": "https://www.instagram.com/humbleandkindcontractors/" },
{ "url": "https://www.instagram.com/igranitehouston/" },
{ "url": "https://www.instagram.com/insinkerator_au_/" },
{ "url": "https://www.instagram.com/iconstruct.ca/" },
{ "url": "https://www.instagram.com/joelcustoms/" },
{ "url": "https://www.instagram.com/jordandesignbuildgroup/" },
{ "url": "https://www.instagram.com/kitchensbyjsg/" },
{ "url": "https://www.instagram.com/kolakliving/" },
{ "url": "https://www.instagram.com/komandorclosets/" },
{ "url": "https://www.instagram.com/ladisicfinehomes/" },
{ "url": "https://www.instagram.com/lakevillecabinets/" },
{ "url": "https://www.instagram.com/lanemyershomes/" },
{ "url": "https://www.instagram.com/larkandlarks/" },
{ "url": "https://www.instagram.com/legacykitchens/" },
{ "url": "https://www.instagram.com/life_kitchens/" },
{ "url": "https://www.instagram.com/trinity_homes/" },
{ "url": "https://www.instagram.com/aspen_homes/" },
{ "url": "https://www.instagram.com/bsnelsonbuilding/" },
{ "url": "https://www.instagram.com/blacdesignandbuild/" },
{ "url": "https://www.instagram.com/brayandscarff/" },
{ "url": "https://www.instagram.com/breven_homes/" },
{ "url": "https://www.instagram.com/caseyconstructionsptyltd/" },
{ "url": "https://www.instagram.com/cambridgehomes_nz/" },
{ "url": "https://www.instagram.com/countertopsofmemphis/" },
{ "url": "https://www.instagram.com/dicharryhomes/" },
{ "url": "https://www.instagram.com/dl_cabinetry/" },
{ "url": "https://www.instagram.com/dreamkitchen_qatar/" },
{ "url": "https://www.instagram.com/envy.homeliving/" },
{ "url": "https://www.instagram.com/esperanzahomes/" },
{ "url": "https://www.instagram.com/fiveeighteenconstruction/" },
{ "url": "https://www.instagram.com/gaylerdesignbuild/" },
{ "url": "https://www.instagram.com/geoffscontracting/" },
{ "url": "https://www.instagram.com/peaklegacyafrica/" },
{ "url": "https://www.instagram.com/hueinteriorsuk/" },
{ "url": "https://www.instagram.com/ilvedanmark/" },
{ "url": "https://www.instagram.com/infinityhubts/" },
{ "url": "https://www.instagram.com/jamesmichaelhomes/" },
{ "url": "https://www.instagram.com/kingsgateconstruction/" },
{ "url": "https://www.instagram.com/kitchenexpresschch/" },
{ "url": "https://www.instagram.com/m_r_designbld/" },
{ "url": "https://www.instagram.com/marrwall/" },
{ "url": "https://www.instagram.com/mbn_properties/" },
{ "url": "https://www.instagram.com/mckbkitchens/" },
{ "url": "https://www.instagram.com/meadowskitchens/" },
{ "url": "https://www.instagram.com/mimosahomes/" },
{ "url": "https://www.instagram.com/nomatickitchens/" },
{ "url": "https://www.instagram.com/planetfurnitureltd/" },
{ "url": "https://www.instagram.com/rdhomesco/" },
{ "url": "https://www.instagram.com/rhchomeimprovements/" },
{ "url": "https://www.instagram.com/se_landscape_construction/" },
{ "url": "https://www.instagram.com/squarekitchensponsford/" },
{ "url": "https://www.instagram.com/stonehengebuilt/" },
{ "url": "https://www.instagram.com/wegnercabinetry/" },
{ "url": "https://www.instagram.com/west4_interiors/" },
{ "url": "https://www.instagram.com/sinnibuildinggroup/" },
{ "url": "https://www.instagram.com/acescustombuilds/" },
{ "url": "https://www.instagram.com/afrikitchens/" },
{ "url": "https://www.instagram.com/alisonzavracky_design/" },
{ "url": "https://www.instagram.com/blankandcodesign/" },
{ "url": "https://www.instagram.com/almabernan/" },
{ "url": "https://www.instagram.com/alt.construction/" },
{ "url": "https://www.instagram.com/amberth_design/" },
{ "url": "https://www.instagram.com/arhomes.orlando/" },
{ "url": "https://www.instagram.com/aristabuildconahmedabad/" },
{ "url": "https://www.instagram.com/armazemdesign.us/" },
{ "url": "https://www.instagram.com/arthousecreativeinteriors/" },
{ "url": "https://www.instagram.com/bandtkitchens/" },
{ "url": "https://www.instagram.com/bainecontracting/" },
{ "url": "https://www.instagram.com/besttile/" },
{ "url": "https://www.instagram.com/betterbuilthomes/" },
{ "url": "https://www.instagram.com/blackmountainconst/" },
{ "url": "https://www.instagram.com/borodidesign/" },
{ "url": "https://www.instagram.com/ryanrealtyteam/" },
{ "url": "https://www.instagram.com/clancy_construction/" },
{ "url": "https://www.instagram.com/thelumenapts/" },
{ "url": "https://www.instagram.com/contempospazio/" },
{ "url": "https://www.instagram.com/corneliusconstruction/" },
{ "url": "https://www.instagram.com/coverups_fergusarthur/" },
{ "url": "https://www.instagram.com/daretodreamprints/" },
{ "url": "https://www.instagram.com/debraadimey/" },
{ "url": "https://www.instagram.com/designkitchenandbath/" },
{ "url": "https://www.instagram.com/discountkitchendirect/" },
{ "url": "https://www.instagram.com/construction_by_maya/" },
{ "url": "https://www.instagram.com/ellesvisuelles/" },
{ "url": "https://www.instagram.com/frontierstroyuk/" },
{ "url": "https://www.instagram.com/gia_renovations/" },
{ "url": "https://www.instagram.com/hausscape/" },
{ "url": "https://www.instagram.com/holtzmanremodeling/" },
{ "url": "https://www.instagram.com/horizon_kbdesign/" },
{ "url": "https://www.instagram.com/hyvehomes/" },
{ "url": "https://www.instagram.com/kitchendesignsolutions/" },
{ "url": "https://www.instagram.com/kitchengroups/" },
{ "url": "https://www.instagram.com/kitchensandmore.uganda/" },
{ "url": "https://www.instagram.com/klugrealtygroup/" },
{ "url": "https://www.instagram.com/lighthouse_contracting_group/" },
{ "url": "https://www.instagram.com/maryannegallodesign/" },
{ "url": "https://www.instagram.com/mcdowellhomes/" },
{ "url": "https://www.instagram.com/modernmatterhardware/" },
{ "url": "https://www.instagram.com/modersy_interior/" },
{ "url": "https://www.instagram.com/radiancekitchensandfurniture/" },
{ "url": "https://www.instagram.com/mrhandyman/" },
{ "url": "https://www.instagram.com/mrhandymancentralnj/" },
{ "url": "https://www.instagram.com/mrhandymancincinnati/" },
{ "url": "https://www.instagram.com/mrhandymancincoranch/" },
{ "url": "https://www.instagram.com/ottawarenovationpro/" },
{ "url": "https://www.instagram.com/pacificnwmarbleandgranite/" },
{ "url": "https://www.instagram.com/panelvenkitchens/" },
{ "url": "https://www.instagram.com/kitchens_by_portfolio/" },
{ "url": "https://www.instagram.com/precisionhomedesignnremodeling/" },
{ "url": "https://www.instagram.com/redinkhomes/" },
{ "url": "https://www.instagram.com/remodelmyhome.ca/" },
{ "url": "https://www.instagram.com/renovatingkc/" },
{ "url": "https://www.instagram.com/rhino_construction_seattle/" },
{ "url": "https://www.instagram.com/romainteriorsashford/" },
{ "url": "https://www.instagram.com/beyondrenovations365/" },
{ "url": "https://www.instagram.com/seconstructioninc_/" },
{ "url": "https://www.instagram.com/simplymodernkitchen/" },
{ "url": "https://www.instagram.com/spatiostudio/" },
{ "url": "https://www.instagram.com/sureline_building_group/" },
{ "url": "https://www.instagram.com/tbc_general_contracting/" },
{ "url": "https://www.instagram.com/tcmconstructiongroup/" },
{ "url": "https://www.instagram.com/tentenkitchens/" },
{ "url": "https://www.instagram.com/thayercontracting/" },
{ "url": "https://www.instagram.com/livethebaxly/" },
{ "url": "https://www.instagram.com/thompsontraders/" },
{ "url": "https://www.instagram.com/totalhomeconstruction/" },
{ "url": "https://www.instagram.com/ellairedesigns/" },
{ "url": "https://www.instagram.com/turnerandsonhomes/" },
{ "url": "https://www.instagram.com/tycon_building_solutions/" },
{ "url": "https://www.instagram.com/valcucinebrasil/" },
{ "url": "https://www.instagram.com/whitesplumbingsupplies/" },

];

// Function to insert seed data
const seedDB = async () => {
  try {
    await Link.deleteMany({}); // Clear existing data
    await Link.insertMany(seedData); // Insert new data
    console.log("Database seeded successfully");
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    mongoose.connection.close(); // Close the connection after seeding
  }
};

seedDB();
